### ISSUE TITLE
[Gen 4] Bug Catching contest / Safari Pokemon on HGSS.

### ISSUE THREAD

**Issue by RichardPaulAstley** [Admiral-Fish/PokeFinder#1]
So first, the links as I told you :  
https://www.reddit.com/r/pokemonrng/comments/2cfxsq/bug_catching_contest_gen_4_rng/
https://www.reddit.com/r/pokemonrng/comments/3ef7c0/bug_catching_contest_rng_without_cute_charm/

And an example of somebody trying without any results : 
http://www.smogon.com/forums/threads/past-gen-rng-research.61090/page-13#post-2987503

Was not able to find something else sadly. Nothing on main guides etc, really something missing.

In RNGReporter, it's known that frames are not displayed correctly. The 4th Gen Time Finder says nothing about this, but when you generate results on the main frame : 

![image](https://user-images.githubusercontent.com/25870563/27363731-8495c6f4-5636-11e7-8bd1-57f05dc0016e.png)

A warning is here about this, but of course, NO FRAME are bold when you check (0 bold in 100k of results). So really there's something wrong about these methods. 

Because the goal of this would be to AVOID Cute Charm which can be difficult to do (in my game for example, i don't have access to this)

And moreover, having the possibility to display GOOD frames would be cool.

For ending, I can tell you my own experience : I've searched for a SHiny adamant Scyther. It was frame 86. I hit the seed correctly of course, I up it to the right frame... And got a pokemon at a frame around 175 higher than excepted.

Thanks o/

**Comment by Admiral-Fish** [comment]
Related to bug catching https://pastebin.com/Y0VRnJxu

**Comment by Admiral-Fish** [comment]
Related to safari zone https://github.com/pret/pokeemerald/blob/1e4f12e6fa9e3b22d4f1a60ca69313b5dec0ca38/src/wild_encounter.c#L310-L336

**Comment by Orionsilver** [comment]
**THANK YOU
U R AWESOME**

**Comment by RichardPaulAstley** [comment]
![image](https://user-images.githubusercontent.com/25870563/57976081-c1a19600-79d8-11e9-930c-4da8d81b7308.png)

Maybe not supported, but checking a random wild will give wrong encounter slots

**Comment by Admiral-Fish** [comment]
https://github.com/shinyfinder/Safari-ES-Calculator/blob/master/index.html

**Comment by RichardPaulAstley** [comment]
1IV seems to be enough to make it working

**Comment by Real96** [comment]
https://github.com/yatsuna827/Pokemon4genRNGLibrary/blob/09bcdd108e7a98fc6acee50e9db78b8bcceb4b45/Pokemon4genRNGLibrary/IndividualGenerator/IIndivGenerator.cs#L67

**Comment by Real96** [comment]
BCC added in ae59637

**Comment by Admiral-Fish** [comment]
Closed this as fixed in the redesign branch

Safari added via 18a5ee4
