### ISSUE TITLE
Unown Method suggestion for FRLG.

### ISSUE THREAD

**Issue by StarfBerry** [Admiral-Fish/PokeFinder#100]
Add the functionality of your unown python script (the one pinned on PokémonRNG discord) in Pokéfinder would be interesting.

The "Unown Method" would be usable only in the 7 chambers and the scrolling menu of the target species would allow the choice of the form.

**Comment by 8Bit-Wolf** [comment]
Pleeeeease...

**Comment by Admiral-Fish** [comment]
Working gen 5 and gamecube stuff for the next while. After that I will consider this.

**Comment by Admiral-Fish** [comment]
Fixed by #289
