### ISSUE TITLE
[Error] Gen 4 Wild Encounter Searcher does not match the Generator

### ISSUE THREAD

**Issue by greenDarkness** [Admiral-Fish/PokeFinder#101]
Currently, Pokefinder's Searcher says seed A5140629 frame 42 is a Jolly 31/31/31/0/31/31 Sneasel if if the user has a Jolly synchronize Pokemon in the lead of their party.
![image](https://user-images.githubusercontent.com/15519892/83661143-b85b7b00-a593-11ea-9077-b8350b7a6108.png)
When data is generated using the seed, frame 42 does not match the Searcher.
![image](https://user-images.githubusercontent.com/15519892/83661582-54858200-a594-11ea-9ba7-cee03a999c65.png)

**Comment by greenDarkness** [comment]
This is also true for fishing as well. Searcher is showing spreads which cannot be generated in the generator for the rod used.

**Comment by Admiral-Fish** [comment]
Thanks for finding the relevant commits

**Comment by greenDarkness** [comment]
No problem. One day I'll do more than just report haha.
