### ISSUE TITLE
Method K Searcher is off by 1

### ISSUE THREAD

**Issue by greenDarkness** [Admiral-Fish/PokeFinder#102]
As of build `0cca865`:
The searcher says seed `94000790` frame `192` for Method K is supposed to be Bold 31/10/30/31/31/31.
![image](https://user-images.githubusercontent.com/15519892/84023573-536aa100-a956-11ea-813d-42d04ba6e7f4.png)
In reality `94000790` frame `192` is Careful 15/30/30/27/21/23 which matches the generator.
![image](https://user-images.githubusercontent.com/15519892/84023620-68dfcb00-a956-11ea-80db-b24631f5d5bf.png)
Frame 193 is correct however, and matches the target spread.

**Comment by Admiral-Fish** [comment]
You verified in game that generator is correct?

**Comment by greenDarkness** [comment]
Yes, I tried to get the spread again, and stopping on frame 192, and talking to the stationary, which would advance the frame by 1, yielded the correct spread.

**Comment by greenDarkness** [comment]
Went back as far as `e0ce4acaddba7cccbaf7ce311770e8f88cbe860a` and I could not find a working build that did method K correctly.

**Comment by Admiral-Fish** [comment]
I am unable to test cute charm, but normal and synch are fine now
