### ISSUE TITLE
Latest version on linux does not open

### ISSUE THREAD

**Issue by Lillievela** [Admiral-Fish/PokeFinder#104]
I downloaded the latest version and when i tried to open it it doesnt open at all, the version before it does, and there is no update message either. Using Manjaro Linux, latest testing

**Comment by Admiral-Fish** [comment]
What version of Qt does Manjaro have?

**Comment by Lillievela** [comment]
5.15.0 as of right now, its the latest one i believe

**Comment by Admiral-Fish** [comment]
What kind of error message is it giving

**Comment by Lillievela** [comment]
There isnt any error, i double click it and it does nothing, its just 2.5.3 that does it, 2.5.2 works just fine

**Comment by Admiral-Fish** [comment]
2.5.3 builds are done on Ubuntu 20.04. I'm not sure if there is some kind of incompatibility with that and Manjaro.

**Comment by Lillievela** [comment]
There might? trying to launch via terminal results in an output of "undefined symbol: _ZdlPvm, version Qt_5" Im not exactly sure, but it seems like its a g++ incompatibility

**Comment by Admiral-Fish** [comment]
Looking online makes it seem like incompatible Qt versions. It might have to be compiled manually on Manjaro.

https://stackoverflow.com/questions/53022608/application-crashes-with-symbol-zdlpvm-version-qt-5-not-defined-in-file-libqt

**Comment by Lillievela** [comment]
Alright, ill try building it on my end, ill close this with an update if i succeed

**Comment by Lillievela** [comment]
Okay yea, it just had to be built locally, guess that solves it, if anyone else has this issue just do a git clone then put qdarkstyle in the folder and build it
