### ISSUE TITLE
[ XD Gales ] Suggestions to include missing information useful for RNGing

### ISSUE THREAD

**Issue by Sephirona** [Admiral-Fish/PokeFinder#105]
Hi there! I'm looking to write an updated guide for XD Gales RNG Shiny Skip and Anti-Shiny that uses Pokefinder, and I was told that I should bring up these issues to you before doing so. While I was RNGing in Gales, I had to use both RNG Reporter and Pokefinder because there are some features available on RNG Reporter that are not yet implemented on Pokefinder. I'd like to only refer to Pokefinder if possible while writing so that it is an up to date guide, since RNG Reporter is out of date. These are my two main suggestions:

1) Perhaps add the TSV needed to be RNGed next to the Shiny Skip spreads. Here is how RNG Reporter does it:
![1](https://user-images.githubusercontent.com/62824439/84818850-29178400-afe5-11ea-8eb6-fb117f34fb19.png)

And here is Pokefinder:

![2](https://user-images.githubusercontent.com/62824439/84818873-303e9200-afe5-11ea-855d-7e85530dc6c6.png)

Being able to see the TSV that is needed is useful since one can calculate an SID using the desired ID number and the TSV if they want a custom ID/SID combo. 

2) Include some manner of highlighting which spreads can be anti-shiny with the resulting natures

When RNGing the Bold 31/0/31/31/31/31 and Timid pair 31/0/31/31/31/31 spreads below, One would not realize while using Pokefinder that these spreads are possible, because only the Rash and Quirky variants are displayed. RNG Reporter displays both the normal and the anti-shiny variants next to each other. Here is how RNG Reporter displays them, blocked in red:

![3](https://user-images.githubusercontent.com/62824439/84819424-f457fc80-afe5-11ea-843c-d337b810a798.png)

And here is how Pokefinder displays it. As you can see, the possible Anti-shiny Timid Bolds are not displayed, and intuitively, no one would know that these spreads could be RNGed anti-shiny. Incidentally, this pair of spreads also works for Zapdos, Moltres, and Articuno, but they are also not searchable at the moment, I think because they are not constrained by Nature Locks and only the NLed mons can be selected in the Pokefinder XD search tab. So at the moment, people would not know that they can search these birds to have the flawless anti-shiny spreads as well.

![4](https://user-images.githubusercontent.com/62824439/84819641-56186680-afe6-11ea-9bae-f758637bf20c.png)

**Comment by Admiral-Fish** [comment]
If I am being completely honest I never liked how I did the original GameCube RNG. I made a number of different design decisions with Pokefinder.

Only Shadows with locks are displayed in the Gales/Colo dropdowns.

The shiny lock is actually handled, but it uses the TID/SID of the current profile.

Anti-shiny and shiny skip were always the most advanced RNG concepts in Gales. I personally can't think of more then 2 people that have done it. There isn't really a graceful way to show the possibilities when you only consider the profile.

**Comment by Sephirona** [comment]
When you say the shiny lock is handled but that it uses the TID/SID of the profile, do you mean that the shininess does show up? Because it does show up properly, but even with a TID/SID combo that would make the Anti-shiny Bold 31/0/31/31/31/31 or Timid 31/0/31/31/31/31 spreads possible, only the Quirky and Rash spreads are displayed, and the user of Pokefinder would not know about the Timid/Bold variants. Here's an example with Pidgeotto, which is one of the mons I successfully RNGed on Dolphin using this method. The ID 00007 and SID of 39528 were RNGed by using Legofigure's SID for shiny site to choose a TID and PID to calculate a needed SID, and then converting those to hex, plugging it into PID to IVs, and then calculating an RTC to start with. I searched for Timid and did not get a result:

![5](https://user-images.githubusercontent.com/62824439/85090776-f66fb600-b1b3-11ea-8787-b111f1b6c1e2.png)

However, searching for the Quirky variant still produces one, correctly marked Shiny because it is the PID that gets skipped to Timid:
![6](https://user-images.githubusercontent.com/62824439/85090847-1901cf00-b1b4-11ea-85ee-b08bdcdeea65.png)

There is similarly no Bold/Timid result displayed even with the default "None" profile and XD/Colo spreads selected. 

Similarly, I can also RNG a custom TID and SID using the displayed TSV from RNG Reporter for Shiny Skip RNGs, but if using Pokefinder alone would need to go in and count upwards from the desired result and hopefully choose the correct PID to RNG a TID/SID for. I was able to learn how to RNG the shiny skip 31/31/31/25/31/31 Salamence only because I had the TSV from RNG Reporter, which I then calculated a TID/SID combo for and could verify using Pokefinder because only then did Pokefinder show me which PID ended up shiny and how the PID rerolled twice on the first shadow after the nature locked mon. 

Anyways, I am hoping to make Shiny-Skip/Anti-shiny RNG at least a little more accessible for others with my guide, and I can still just refer to both your work in RNGReporter and in Pokefinder to do so! It is just not yet possible to only pick up Pokefinder and be able to figure out how to do this with Pokefinder alone, which is why I thought I might bring it to your attention. Thank you for your fantastic work on both programs nonetheless n_n

**Comment by Admiral-Fish** [comment]
Thank you for reporting this in the searcher. Gales gets properly shiny locked in the Generator, but not the Searcher. I will correct this soon.

**Comment by Sephirona** [comment]
Actually, I'm not sure if the shiny lock works properly in the generator either as the possible Anti-shiny result is also not displayed there ^^; That's why I assumed it wasn't an added feature. Here are some pictures again using the TID/SID that would work for the Quirky->Timid spread. The seed was generated using "Generate Seed to Time" from the Quirky search result:

With XD/Colo selected, only the Quirky is displayed shiny with those IVs. The Timid variant is still not displayed despite the Nature filter not being checked:

![7](https://user-images.githubusercontent.com/62824439/85209441-0f887c00-b306-11ea-92dd-b430195bd7df.png)

With Pidgeotto selected, the Quirky shows up, and it is not shiny, which makes sense since Pidgeotto would never be shiny. But the Timid possibility is still not displayed with those IVs and that TID/SID combo, so there's still no indication that that spread is possible. Incidentally, I would even say that the Quirky being displayed Shiny helps, especially when using the XD/Colo tab, because the user then knows to look two frames after the Quirky to see the actual PID they would land on:

![8](https://user-images.githubusercontent.com/62824439/85209496-802f9880-b306-11ea-9e2d-0b6547626f7f.png)

Finally, here's a screenshot of what I did when I successfully RNGed the Pidgeotto. I had to use the XD/Colo tab to understand that the Quirky would be rerolled two frames later into a Timid with the Quirky spread's IVs, which I knew about since I learned of the spread in RNG Reporter. The Timid PID is indeed displayed, but with its native not-anti-shiny IVs. Of course, the native Timid PID and spread can still be hit even with a TID/SID rnged file, so it's still good to know about and so it would be the responsibility of the RNGer to calculate the number of frame jumps that happened to make sure they landed on the right variant of the PID:

![9](https://user-images.githubusercontent.com/62824439/85209522-bb31cc00-b306-11ea-8f45-aa7e1ed9aba6.png)

Thanks! I'm sure you've got a lot on your hands what with the new DLC being released and all, and I'm aware XD RNG is rather old and less commonly done than the other types, so no rush or anything n_n

**Comment by Sephirona** [comment]
Also, as an addendum, here's how RNG Reporter displays it, which is how I knew that the Quirky and Timid 31/0/31/31/31/31 exist on the same seed and therefore must be related:

![10](https://user-images.githubusercontent.com/62824439/85210115-3301f580-b30b-11ea-815a-163e5ec76bae.png)

**Comment by Admiral-Fish** [comment]
Commits ea784c4 and 72fda88 should address most of this

**Comment by Sephirona** [comment]
Hey, thank you for the updates to Pokefinder! I just took a look at version 2.5.4. I can see that you have made it so that Anti-shiny and shiny-skip spreads are only displayed in the Searcher if one has a matching TID/SID combo to make those spreads possible. However, there is an issue with this. People who do not yet have the TID/SID combo already would not know of these spreads while using the Searcher, and would therefore still not actually know they exist. I still feel that the way you marked the TSVs next to shiny-skip spreads in RNGReporter made it a lot clearer what should be RNGed, so people would know what to aim for by calculating their needed SID from that TSV. As it stands, it is still not possible to pick up Pokefinder and know that these anti-shiny spreads are possible, since people would have to learn from RNGReporter first and use it to figure out what TID/SID combo to get before they can use Pokefinder to do the RNG.

**Comment by Admiral-Fish** [comment]
Sorry for late response. In regards to not showing the required TSV for shiny skip or anti-shiny I left my opinions above.

 >The shiny lock is actually handled, but it uses the TID/SID of the current profile.

>Anti-shiny and shiny skip were always the most advanced RNG concepts in Gales. I personally can't think of more then 2 people that have done it. There isn't really a graceful way to show the possibilities when you only consider the profile.

These opinions lead to design decisions where I can't easily show the TSV where as the original GameCubeRNG took a different approach which I never fully liked.

Long story short, it will remain the way it is.
