### ISSUE TITLE
[Feature request] Filtered iv range

### ISSUE THREAD

**Issue by Liger0** [Admiral-Fish/PokeFinder#107]
A thing that would be useful is to have the possibility to see directly the sum of IVs and being able to order the spread list based on that.
Furthermore, it would be useful to select the interested ivs that the sum would take care of.
For example, if I want a pokemon that has a low atk for a special attackers or low speed for trick rooms, I would be able to specify a range of atk or speed of 0-5.
Then, I consider the sum of ivs to see which one is the best I can have. The problem is that, in this case, you can't just consider the one with highest ivs, because the lowest the atk/speed, the best the spread is. Or in general, you may not care about an unused iv.
So, excluding the atk or speed (or anything else) from the iv sums upon specification would be ideal.
So my idea would be a dropdown to check the wanted ivs to filter, and then an iv range wanted.
The spread list generated will then report the filtered ivs sum and can by clicked to order it.

**Comment by Admiral-Fish** [comment]
This can already be accomplished by the existing IV filters. Am I missing something?

**Comment by Liger0** [comment]
I don't see an IVs Sum field, especially one where you can specify which ivs to sum.

**Comment by Admiral-Fish** [comment]
I don't understand how a IV sum filter would be beneficial. What benefit does it give to users of the program?

**Comment by Liger0** [comment]
For things that have limited spreads for example, like gen 3 events and such, where you may not have all at 30/31 but you just want spreads that have the best sums. Y
ou may set all >=28 and you may find all at 28, but with a sum range you can find a spread that has some points less in one stat and all the rest at 30/31.

**Comment by Admiral-Fish** [comment]
I will not implement this. Will accept pull requests if anyone is interested enough.
