### ISSUE TITLE
[feature request] Portable game profiles

### ISSUE THREAD

**Issue by Liger0** [Admiral-Fish/PokeFinder#109]
It would be good to have a standalone config file for the profiles.
This way you can just use the program from an usb on any pc, and avoid to permanently store the values in the registry.

**Comment by Admiral-Fish** [comment]
I'm not opposed to doing this and it doesn't seem like a bad idea for portability. That being said, reading through the documentation of QSettings does not seem like it will make this easy given my current approach. I will probably have to make a wrapper class around QSettings that gives me a little bit more control.
