### ISSUE TITLE
Seed Saving

### ISSUE THREAD

**Issue by ShinySylveon04** [Admiral-Fish/PokeFinder#11]
Some way to save seeds that correspond to profiles or IDs/SIDs. Would save time searching if forget or lose seed. Very handy for ID/SID RNGing for specific PIDs.

No rush for this, just an idea :)

**Comment by zaksabeast** [comment]
This is a great idea - I currently have a text document dedicated to this.  Having a dedicated portion of PokeFinder would be awesome.

**Comment by Admiral-Fish** [comment]
Related to #6. Can probably link to profiles or something.

**Comment by Admiral-Fish** [comment]
It's been long enough that I don't see myself doing this. Closing, but feel free to open a PR if you really want to see it.
