### ISSUE TITLE
[Gen 5] Gen 5 egg window too big

### ISSUE THREAD

**Issue by AyanamiRei1** [Admiral-Fish/PokeFinder#112]
The window is currently too big for anyone under 1080p basically any laptop that's not a gaming one.
![image](https://user-images.githubusercontent.com/25233407/87755786-8dee1600-c7ff-11ea-8c12-3fa0101978d8.png)

**Comment by Admiral-Fish** [comment]
My laptop has some rather weird screen settings which has it made it interesting to test on a difference screen size. I'll try to locate another laptop that I can test on.

That being said, are you able to resize and make the window smaller?

**Comment by Admiral-Fish** [comment]
See aed27c9
