### ISSUE TITLE
Dark mode on Mac

### ISSUE THREAD

**Issue by GimmyTomas** [Admiral-Fish/PokeFinder#116]
It appears that, when Dark mode is on (on Mac), it is not possible to click on the buttons on the gui.

**Comment by matthewleong** [comment]
I'm reporting the same issue as well. Dark mode doesn't allow me to click any of the buttons - I have to disable dark mode and then manually quit and reopen the app. Big Sur.

**Comment by mleong245** [comment]
I'm reporting the same issue as well. Dark mode doesn't allow me to click any of the buttons - I have to disable dark mode and then manually quit and reopen the app. Big Sur.

**Comment by Admiral-Fish** [comment]
This should be fixed as of PokeFinder 3.0.0 using Qt 5.12.2. Release will be out soon
