### ISSUE TITLE
GameCube RTC Cancel button doesn't work

### ISSUE THREAD

**Issue by Real96** [Admiral-Fish/PokeFinder#120]
If you start searching using GameCube RTC, you can't cancel the research cause Cancel button doesn't work.
It stays as showed in the following screen until it finds a result:

![image](https://user-images.githubusercontent.com/20956021/92719942-333aeb80-f364-11ea-874e-22841d1325a7.png)

**Comment by Admiral-Fish** [comment]
Unable to replicate on latest commit (60ebf88)

**Comment by Real96** [comment]
> Unable to replicate on latest commit ([60ebf88](https://github.com/Admiral-Fish/PokeFinder/commit/60ebf883dfa262e4ae7313ddf6569059516b1750))

It is still present in last commit. Do you need a video or something? After Cancel pressing, it stays as the screen i sent above

**Comment by Admiral-Fish** [comment]
I understand what you are saying. What I'm saying is nothing in the code would leave me to believe that cancel doesn't work.

**Comment by Real96** [comment]
What do you think can be the issue?

**Comment by Admiral-Fish** [comment]
The only thing I can see is that I only check for cancelling after each "second" of RTC processing. So I suppose if you put max advances high enough it could appear to be not cancel, but even then I don't think it would cause enough of a bottleneck to appear noticeable.

I made a couple changes though. Let me know if it works better.

**Comment by Real96** [comment]
Ok just checked.
The cancel button works, it stop the research correctly. But sometimes the app crashes if i click it. Also if i want to get 1 Jan 2000 i must set 2 Jan 2000 (this is surely due to timezones)

**Comment by Admiral-Fish** [comment]
Original issue fixed. Closing in favor of #163 for the crash
