### ISSUE TITLE
User Profiles Are Unusable

### ISSUE THREAD

**Issue by greenDarkness** [Admiral-Fish/PokeFinder#122]
Commit d24cf92ac794bad9b16c958da6fbe2e29407dfd0 of Pokefinder cannot use, save, or load profiles for Gen 4. 
My users profiles on an earlier build of Pokefinder appear to be gone after launching this version as well.

**Comment by Admiral-Fish** [comment]
Unable to replicate. Please provide your profiles.json file.

Please note that the recent profile change is a breaking change. Do not attempt to mix version of Pokefinder as it migrates the old profile format to the new profile format and then deletes the old storage method. See 2b214f2

**Comment by greenDarkness** [comment]
You described what I did; I have been mixing and matching my Pokefinder versions. I'm sure that was the cause.
But I'll post my profiles.json, and attempt to recreate just in case.
Profiles.json: (placeholder)
