### ISSUE TITLE
Finding GC seeds take too long in last version (2.5.4)

### ISSUE THREAD

**Issue by zetalink** [Admiral-Fish/PokeFinder#135]
I read on the last release notes that you don't need colo.precalc anymore, but searching for seeds takes forever like old versions when they didn't have the precalc file.
Also adding the precalc file to the folder of this new version doesn't change anything, still takes a lot of time (so indeed, it's not using it).
I'm using an old version to find seeds but I hope this can be fixed, or maybe is a problem I have in my pc

**Comment by Admiral-Fish** [comment]
d26aa87
