### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Elite2021** [Admiral-Fish/PokeFinder#140]
I can not get the app to open up any ideas on why? I did try reinstalling it three times as well.

<img width="960" alt="Screenshot 2021-02-02 055445" src="https://user-images.githubusercontent.com/76456395/106603250-4caf2080-651b-11eb-9015-fd61320bcfee.png">

**Comment by Admiral-Fish** [comment]
From the release notes:

If you download a windows build you might need to install the c++ redistributable. You can find the download page [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).

**Comment by Elite2021** [comment]
> From the release notes:
> 
> If you download a windows build you might need to install the c++ redistributable. You can find the download page [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).

Thank you it is working now. I appreciate the help.
