### ISSUE TITLE
profile manager not working

### ISSUE THREAD

**Issue by Elvundil** [Admiral-Fish/PokeFinder#143]
profile manager does not save profiles on 3.0

**Comment by Admiral-Fish** [comment]
Try looking at Tools>Settings (or PokeFinder>Preferences on mac) and see where the Profiles Path is set as. This may need to be changed.

**Comment by Elvundil** [comment]
(I have windows (pokefinder on SSD)) I tested that its does not work the profiles are not kept in memory ,this create a profiles.json file but when I create a profile once I click on done and go back to the profile manager it's empty nothing was saved.I don't have this problem on the older version.

**Comment by Real96** [comment]
> (I have windows (pokefinder on SSD)) I tested that its does not work the profiles are not kept in memory ,this create a profiles.json file but when I create a profile once I click on done and go back to the profile manager it's empty nothing was saved.I don't have this problem on the older version.
> 
> **edit 1**: I just tested to put the profiles.json file on a hard drive (not ssd) it works so at first I thought it came from the fact that I saved on my ssd but I tried to put the profiles file .json elsewhere on the same ssd it works i think the file path was too long (i have a path like this ("E: \ folder1 \ folder2 \ PokeFinderwindows2.5.4 \ PokeFinderwindows3.0" its not works) (while with a path like this "E: \ folder1 \ profiles.json" works) by shortening the path it seems to have worked well

Check if there are some folders in the path with an accent in the name. They caused problem to me

**Comment by Elvundil** [comment]
no accent  but I have this"_" '(folder name is "poke_fodler")in a folder name I remove the "_" and it's works fine now

**Comment by Real96** [comment]
> no accent but I have this"_" '(folder name is "poke_fodler")in a folder name I remove the "_" and it's works fine now

It seems that the problem are not ordinary letters in folder names

**Comment by Admiral-Fish** [comment]
I have not been able to find much about what is a valid filename and what isn't https://doc.qt.io/qt-5/qfile.html

**Comment by Elvundil** [comment]
I realized on 2 pc that the problem of unsaved profile only appears when the pokefinder folder is in my download folder if the profile.json file is stored elsewhere than in the download folder it works without problem. I do not know if I am the only one to have this problem but I was able to reproduce the same thing on another pc.

**Comment by Real96** [comment]
> I realized on 2 pc that the problem of unsaved profile only appears when the pokefinder folder is in my download folder if the profile.json file is stored elsewhere than in the download folder it works without problem. I do not know if I am the only one to have this problem but I was able to reproduce the same thing on another pc.

Do you have PokeFinder in download folder?

**Comment by Elvundil** [comment]
yes but if I copy the folder elsewhere it works fine with the profils.json file in my pokefinder folder.

**Comment by Real96** [comment]
> yes but if I copy the folder elsewhere it works fine with the profils.json file in my pokefinder folder.

The thing is that for me this doesn't work. Do you use the profile in the same folder of Pokefinder when yo

**Comment by Elvundil** [comment]
yes and it's work fine .
![pokefinder](https://user-images.githubusercontent.com/79280679/111040978-3bb8cf80-8436-11eb-9c0a-9a0432e7ac48.png)

if it's like the picture and its also works if the pokéfinder folder is in download and the profiles.json file is saved elsewhere ("D:\profils.json" and pokéfinder folder is "D:\download\PokeFinderwindows" work) .

**Comment by tripodface** [comment]
Though profile manager saves profiles without issue PokeFinder won't load any saved Colo/XD profile.

**Comment by Admiral-Fish** [comment]
Looks like this was resolved by changing path to not include spaces or special characters.

Please reopen or make another issue if there is any follow up problems.

**Comment by rejji76** [comment]
> (I have windows (pokefinder on SSD)) I tested that its does not work the profiles are not kept in memory ,this create a profiles.json file but when I create a profile once I click on done and go back to the profile manager it's empty nothing was saved.I don't have this problem on the older version.
> 
> **edit 1**: I just tested to put the profiles.json file on a hard drive (not ssd) it works so at first I thought it came from the fact that I saved on my ssd but I tried to put the profiles file .json elsewhere on the same ssd it works i think the file path was too long (i have a path like this ("E: \ folder1 \ folder2 \ PokeFinderwindows2.5.4 \ PokeFinderwindows3.0" its not works) (while with a path like this "E: \ folder1 \ profiles.json" works) by shortening the path it seems to have worked well

I went to Gen8 Tools and set the profile that way and when i went into the egg tool i was going to use my profile was there to pick
