### ISSUE TITLE
undefined symbol: _ZdlPvm, version Qt_5

### ISSUE THREAD

**Issue by B0redBanana** [Admiral-Fish/PokeFinder#145]
When I try to run the latest Pokefinder on PopOS 20.10, I get the error "symbol lookup error: /home/*USER*/Desktop/PokeFinder: undefined symbol: _ZdlPvm, version Qt_5"

No idea what I'm supposed to do.

**Comment by Admiral-Fish** [comment]
Do you have Qt 5.14 installed?

**Comment by B0redBanana** [comment]
qmake --version gives me

QMake version 3.1
Using Qt version 5.14.2 in /usr/lib/x86_64-linux-gnu

So, I think so

**Comment by Admiral-Fish** [comment]
Is PopOS compatible with Ubuntu 20.04? That is what my builds are done on.

**Comment by B0redBanana** [comment]
Guess I'll give it a try on PopOS 20.04 then. I'm currently on 20.10

**Comment by Admiral-Fish** [comment]
Closing, please reopen if this is still an issue.

**Comment by TLATER** [comment]
Seeing the same on ubuntu 20.10, using qt 5.14.2 - guess there's an incompatibility between qt versions packaged under ubuntu-based distros between 20.04 and 20.10?
