### ISSUE TITLE
[Gen 3] Breeding Pickup Advances doesn' t matches for Split method.

### ISSUE THREAD

**Issue by Parzival5** [Admiral-Fish/PokeFinder#150]
I tried to get a Split ivs spread but my result doesn't matches with PokéFinder.
I checked with Researcher and the 16bit high of my target pid is not found at the indicated index.

Example:
![Screenshot_11](https://user-images.githubusercontent.com/65578604/113358236-b5f9b700-9345-11eb-98f0-aae4929e3610.png)

I look a little further and I don't get something that matches with my result. 
Normal and Alternate methods work well.

**Comment by Parzival5** [comment]
There must be a bad rng call somewhere that just occurs for the split method.

![Screenshot_14](https://user-images.githubusercontent.com/65578604/114583570-06e0a800-9c82-11eb-8432-24fe8b1d8516.png)

**Comment by Admiral-Fish** [comment]
Is this still an issue?

**Comment by Parzival5** [comment]
Yes, tested with the last commit.
1 in 2 eggs is skipped only for the split method.
This issue seems to have appeared after the 2.4.2 version.

![Screenshot_5](https://user-images.githubusercontent.com/65578604/124130683-5499cf00-da7f-11eb-9731-a8e2e2518a96.png)

**Comment by Parzival5** [comment]
It's caused by the iv2 that advances the main rng.

https://github.com/Admiral-Fish/PokeFinder/blob/master/Source/Core/Gen3/Generators/EggGenerator3.cpp#L372

Credit to lincoln#0442 from the RNG discord who has noticed it.

**Comment by Real96** [comment]
> It's caused by the iv2 that advances the main rng.
> 
> https://github.com/Admiral-Fish/PokeFinder/blob/master/Source/Core/Gen3/Generators/EggGenerator3.cpp#L372
> 
> Credit to lincoln#442 from the RNG discord who has noticed it.

I think it is now fixed in last commit. Isn't it?

**Comment by Admiral-Fish** [comment]
It should be. Unless there is another issue I am unaware of.

**Comment by Admiral-Fish** [comment]
Gonna close this one. If there is another problem please open another issue.
