### ISSUE TITLE
Cancel not working for ProfileSearcher5

### ISSUE THREAD

**Issue by RainingChain** [Admiral-Fish/PokeFinder#153]
ProfileSearcher5::search doesn't check whether searching is false.

Side-note: ProfileSearcher5::cancelSearch() is not thread-safe.
bool searching; should be std::atomic<bool>

**Comment by Admiral-Fish** [comment]
I know it's not thread-safe. But only 1 thing can change the value and only 1 thing reads the value so I don't think it is a big deal.
