### ISSUE TITLE
[Gen 4] Cannot find PID with Ability=1

### ISSUE THREAD

**Issue by malvarenga123** [Admiral-Fish/PokeFinder#158]
Hi, I was trying to find the PID of a legal Gible that I caught and wasn't able to find it in PokeFinder if ability is set to 1.
I can generate the correct PID if ability is set to 0.
![image](https://user-images.githubusercontent.com/61893389/117194174-24ed8400-adba-11eb-852c-6497e8b9dbc0.png)
![image](https://user-images.githubusercontent.com/61893389/117194226-359dfa00-adba-11eb-9b32-e78ba16665ac.png)
![image](https://user-images.githubusercontent.com/61893389/117194381-6bdb7980-adba-11eb-93fd-6fe9f2ddcd19.png)
![image](https://user-images.githubusercontent.com/61893389/117194441-7d248600-adba-11eb-8f11-40a46f9c101e.png)

**Comment by Admiral-Fish** [comment]
PKHex uses 1/2 for abilities while Pokefinder uses 0/1

**Comment by malvarenga123** [comment]
Thanks @Admiral-Fish. Is there any particular reason for this difference between the two programs?
