### ISSUE TITLE
Is the search with Suction Cups correct?

### ISSUE THREAD

**Issue by GimmyTomas** [Admiral-Fish/PokeFinder#160]
I am sorry in case I am doing something wrong. It seems to me that the generator and the searcher are reporting different results for fishing with Suction Cups lead. In particular, the generator gives the correct result (tested on console), while the frame given by the searcher is lower by 2, and attaches the IV spread of the correct frame to the encounter slot of frame-2.

Edit: in other cases, the search finds results with Suction Cups that do not exist in the list shown by the generator.

For example:
<img width="1193" alt="Schermata 2021-05-31 alle 19 41 39" src="https://user-images.githubusercontent.com/23743163/120227180-fa6fd900-c248-11eb-9cda-6321714ee5e0.png">
<img width="1193" alt="Schermata 2021-05-31 alle 19 42 16" src="https://user-images.githubusercontent.com/23743163/120227191-fc399c80-c248-11eb-9879-39c8fd1301a1.png">

**Comment by Admiral-Fish** [comment]
Fixed via 4f8b5c3
