### ISSUE TITLE
Colosseum e-reader generator wrong results

### ISSUE THREAD

**Issue by Real96** [Admiral-Fish/PokeFinder#161]
Colosseum e-reader research has been broken after PokeFinder 2.5.4
The left window is PokeFinder 2.5.4 with correct natures and PIDs, the right window is the last PokeFinder release with wrong natures and PIDs. Mareep is Mild fixed as showed in the left window. Same wrong results also for all the other Colosseum e-reader pokemon. Researcher is correct instead (IVs aren't set to 0, but natures+PIDs are correct there)

![image](https://user-images.githubusercontent.com/20956021/121776480-60375b80-cb8d-11eb-8de1-df25652f67f7.png)

**Comment by Admiral-Fish** [comment]
Is it just E-Reader? Are other shadows for gales and colo impacted?

Initial guess is that I need to reverse the order the locks are looked at for generator. They are stored in reverse order

**Comment by Real96** [comment]
> Is it just E-Reader? Are other shadows for gales and colo impacted?
> 
> Initial guess is that I need to reverse the order the locks are looked at for generator. They are stored in reverse order

It seems that also XD shadow are impacted by this. I just compared 2.5.4 with last commit and they're different

**Comment by Real96** [comment]
Fish did you change this also in colo? Cause i see different results also there, the commit changed only XD method it seems
