### ISSUE TITLE
Threading issue: Spam search/cancel

### ISSUE THREAD

**Issue by Admiral-Fish** [Admiral-Fish/PokeFinder#163]
Spamming search and cancel repeating for what appears to be any search type crashes PokeFinder. Appears to be some kind of heap corruption. This issue will track any updates/progress.

**Comment by Admiral-Fish** [comment]
HEAP[PokeFinder.exe]: Heap block at 000001F17EA530D0 modified at 000001F17EA53130 past requested size of 50
HEAP[PokeFinder.exe]: Invalid address specified to RtlFreeHeap( 000001F17C680000, 000001F17EA530E0 )
Debug Error!

Program: ...op_Qt_5_15_2_MSVC2019_64bit-Debug\Source\Forms\PokeFinder.exe

HEAP CORRUPTION DETECTED: after Normal block (#96864) at 0x000001F17EB240D0.
CRT detected that the application wrote to memory after end of heap buffer.

**Comment by Admiral-Fish** [comment]
Can no longer reproduce on release 4.0.0. Will close if the next release doesn't have the issue as well

**Comment by Real96** [comment]
This unfortunately still happens, but less frequently

**Comment by Admiral-Fish** [comment]
I can no longer reproduce this on 4.1.2
