### ISSUE TITLE
[Gen5] Parameters searcher never ending research

### ISSUE THREAD

**Issue by Real96** [Admiral-Fish/PokeFinder#164]
Research got stuck at a certain percentage with showed parameters

![image](https://user-images.githubusercontent.com/20956021/123561085-bbc93200-d7a6-11eb-89ce-93740dc108d7.png)

**Comment by Admiral-Fish** [comment]
Initial guess is that the variable that stores progress gets overflowed or something.

**Comment by Real96** [comment]
> Initial guess is that the variable that stores progress gets overflowed or something.

Tested [a6f0b3a](https://github.com/Admiral-Fish/PokeFinder/tree/a6f0b3aa3db3b71bd9fbb0c1755df90a4a11b4c4), this time the progress bas is fixed at 0 and the research never stops as before

**Comment by Admiral-Fish** [comment]
Appears to be an infinite loop

**Comment by Real96** [comment]
> Appears to be an infinite loop

Exactly, but if you set FE as max VCount limit, as showed in my previous message, everything works perfectly

**Comment by Admiral-Fish** [comment]
Fixed by https://github.com/Admiral-Fish/PokeFinder/commit/aa099b3a264257f5dad44fdb51eb6234a7da3518

I typoed the issue so it didn't auto close
