### ISSUE TITLE
[Gen4] Occidentary is costantly wrong

### ISSUE THREAD

**Issue by Real96** [Admiral-Fish/PokeFinder#165]
Tested in game. Pokefinder shows occidentary costantly -2 than the real in game value.

**Comment by Admiral-Fish** [comment]
Did you try all cases? Fishing, water, grass, etc.

**Comment by Real96** [comment]
> Did you try all cases? Fishing, water, grass, etc (DPPt vs HGSS).

Just tryed normal grass wilds. I can try all the other encounters

**Comment by Real96** [comment]
> Did you get a chance to try the others?

Yes. This is what i found (made many tests for any of them, always costant errors).

HGSS:
Wild -2
Fishing -3
Surfing -1
Rock Smash -1

DP:
Wild -5
Fishing -6
Surfing -5

Pokefinder is showing always a lower frame than the on in real game

**Comment by Real96** [comment]
Fixed in #182
