### ISSUE TITLE
Search results for Regular Genderless Pokemon in Slot 1 in Dream Radar seed searcher inaccurate

### ISSUE THREAD

**Issue by PokemonTrainerEmily** [Admiral-Fish/PokeFinder#177]
When attempting to RNG a Rotom at Slot 1 in Dream Radar, its nature doesn't match that of what's displayed in PokeFinder (I got Docile instead of Timid).
![206d6bf2d3fa0039da5fa914fa92ba3f](https://user-images.githubusercontent.com/90029196/131970101-7a2b42f8-50b8-43c8-8e9b-99d21286caa6.png)
![19104129dfd785c2b02bafff69e8afb0](https://user-images.githubusercontent.com/90029196/131970188-18c802b3-a6b4-4530-8a11-25a3f69d87bb.png)

Also when changing the Pokemon at Slot 1 to something with a gender, the seed results are exactly as it is when searching for a genderless one. Since genderless ones have an offset of 1 and gendered mons have an offset of 2, the seed results should be different.

BTW, no problems at all when RNGing Legends even if they're genderless. The issue only happens on regular non-legendary genderless ones.

**Comment by SteveCookTU** [comment]
Thank you for bringing awareness to the issue. Can you post a screenshot of the pokefinder window including your settings and filters?

**Comment by SteveCookTU** [comment]
#179 Should fix the issue. If possible, download the artifact from the appveyor build and test the results with your parameters. I don't have a setup to test a full RNG at the moment for accuracy
