### ISSUE TITLE
[Gen 4] Rocksmash encounter advances are sometimes wrong

### ISSUE THREAD

**Issue by Real96** [Admiral-Fish/PokeFinder#180]
Using PokeFinder advances to trigger battle will instead lead you sometime to get an item or nothing. In that case, using Pokefinder advances + 1 will trigger the encounter with the showed IVs.
This happens in both generator and searcher.

**Comment by Real96** [comment]
Fixed in #182

**Comment by Admiral-Fish** [comment]
Can you provide an example?

**Comment by Real96** [comment]
> Can you provide an example?

![image](https://user-images.githubusercontent.com/20956021/140318173-f1d5074e-fee5-4a38-a04d-76eefb80c4e0.png)

Advances 211 gave me an Heart Scale. All the other gave me the correct encouter instead

**Comment by Real96** [comment]
![image](https://user-images.githubusercontent.com/20956021/140318954-8b779de6-1a9a-45be-a0fb-993dde548e95.png)

Advances 222 didn't triggered the encounter. Advances 223 gave me instead the encounter of Advances 222

![image](https://user-images.githubusercontent.com/20956021/140319029-bb0c6fb5-53d3-4482-bca9-b2aafe11494f.png)
