### ISSUE TITLE
Held items

### ISSUE THREAD

**Issue by Admiral-Fish** [Admiral-Fish/PokeFinder#183]
add the thing

**Comment by RichardPaulAstley** [comment]
Gen 4 : % 100 of the Occidentary +4 16BitHigh

(will update that later)

**Comment by Real96** [comment]
Gen4 held items added in #196

**Comment by Real96** [comment]
Gen5: https://www.smogon.com/forums/threads/past-gen-rng-research.61090/page-29#post-3551276

It will need gen5 wilds to be enabled first

**Comment by Admiral-Fish** [comment]
Closed since implementation of #196. Gen 5 will have it added when wild support is implemented
