### ISSUE TITLE
[Gen 5] IDs Generator should ignore the 0x80000000 xor decision

### ISSUE THREAD

**Issue by Parzival5** [Admiral-Fish/PokeFinder#190]
With 0xC0CAC01A pid and 20698 tid, PokéFinder also displays sids that makes 0x40CAC01A to be shiny.
If the 0x8000000 xor decision happened, sids from PokéFinder will make the pid before the xor to be shiny not the target pid.

![Screenshot_1](https://user-images.githubusercontent.com/65578604/133983570-d69d80fc-1049-4b43-b7ac-9222a518fdc3.png)

An other example: if I'm planning to do a breeding rng and I choice to get 0x88888888 pid.
With breeding, the xor decision doesnt occurs and in some case the only result displayed by PokéFinder will be wrong.

![Screenshot_2](https://user-images.githubusercontent.com/65578604/133983627-36129396-f8c3-4558-b31b-2d6834167906.png)

Maybe it would be wise to indicate to the user if the xor occurs or not in case he wants to do a wild/stationary rng.

**Comment by Real96** [comment]
Fixed in 2b0e6f4

**Comment by Parzival5** [comment]
But half of the possible sids are still skipped.
PokéFinder displays sids to get the target pid without the xor but it's possible to obtain it with.
In the previous example with 0xC0CAC01A pid and 20698 tid, all sids displayed are odd.
But if I have 20492 sid and I hit pid 0x40CAC01A, the xor will occurs and I will get the desired pid.

**Comment by Real96** [comment]
> But half of the possible sids are still skipped.
> PokéFinder displays sids to get the target pid without the xor but it's possible to obtain it with.
> In the previous example with 0xC0CAC01A pid and 20698 tid, all sids displayed are odd.
> ![Screenshot_3](https://user-images.githubusercontent.com/65578604/134221865-91f70f1a-3a52-49c9-a1bb-536fa2b75a98.png)
> But if I have 20492 sid and I hit 0x40CAC01A pid, the xor will occurs and I will finally get the desired pid.

Is the proble for egg like rng only then? where the xor doesn't occur?

**Comment by Parzival5** [comment]
Oups I made some mistakes in my previous posts.
But yeah it concern all type encounters wich doesnt follow the pattern HPID^LPID^LTID^LSID == 0 like egg, gift, event.
A button that appears if PID is checked to ask if it's wild/stationary would be fine.

**Comment by Real96** [comment]
> Oups I made some mistakes in my previous posts.
> But yeah it concerns all type encounters wich doesnt follow the pattern HPID^LPID^LTID^LSID == 0 like egg, gift, event.
> A button that appears if PID is checked to ask if it's wild/stationary would be fine.

Fixed here e32a150 and here 90c4e98
Let us know if you find anything wrong!

**Comment by Parzival5** [comment]
When Stationary/Wild is checked, the xor is not ignored.
![Screenshot_2](https://user-images.githubusercontent.com/65578604/134408112-6bb15e30-4adb-4bfa-9c40-d253894fe188.png)
In this case we just have to check if idBit ^ pidBit == 0 like in one of the previous commit.
Otherwise the IDs searcher works fine.

**Comment by Real96** [comment]
> When Stationary/Wild is checked, the xor is not ignored.
> ![Screenshot_2](https://user-images.githubusercontent.com/65578604/134408112-6bb15e30-4adb-4bfa-9c40-d253894fe188.png)
> In this case we just have to check if idBit ^ pidBit == 0 like in one of the previous commit.
> Otherwise the IDs searcher works fine.

Isn't this correct? Wild/stationary will let you get the PID with that ids combo

**Comment by Parzival5** [comment]
In these cases the sid will make the xored pid to be shiny not the pid specified by the user.


> Fixed in [2b0e6f4](https://github.com/Admiral-Fish/PokeFinder/commit/2b0e6f4462e9c795ef89a121fca86175711a2c16)

It had been fixed in this commit.

**Comment by Real96** [comment]
> In these cases the sid will make the xored pid to be shiny not the pid specified by the user.
> 
> > Fixed in [2b0e6f4](https://github.com/Admiral-Fish/PokeFinder/commit/2b0e6f4462e9c795ef89a121fca86175711a2c16)
> 
> It had been fixed in this commit.

Oh damn i think i got it now. You mean that the 88888 will be xored, right?

**Comment by Parzival5** [comment]
Yes, at the end the user will not be able to get the desired pid with some of these ids combo.
In Gen 5 for Wild/Stationary, only half of possible sids are usable with a given tid to make a pid to be shiny.
In this case, PokéFinder should display sids that all share the same parity like in the 0xC0CAC01A screen.

**Comment by Real96** [comment]
> Yes, at the end the user will not be able to get the desired pid with some of these ids combo.
> In Gen 5 for Wild/Stationary, only half of possible sids are usable with a given tid to make a pid to be shiny.
> In this case, PokéFinder should display sids that all share the same parity when pid/tid are specified.

Fixed here fb9ddbc
