### ISSUE TITLE
[Gen 3] Missing FRLG Lost Cave from Locations

### ISSUE THREAD

**Issue by Real96** [Admiral-Fish/PokeFinder#193]
Lost Cave + all his encounterslots are missing in wild window

**Comment by Admiral-Fish** [comment]
https://github.com/pret/pokefirered/blob/master/src/data/wild_encounters.json
https://github.com/pret/pokefirered/blob/master/include/constants/map_groups.h

**Comment by Real96** [comment]
Fixed in f5be595
