### ISSUE TITLE
Emerald Egg Generator Displaying 0 Advances

### ISSUE THREAD

**Issue by LegoFigure11** [Admiral-Fish/PokeFinder#201]
Tested on the windows appveyor build of 14eb361d9509c108bab6e0db2dd3c96ef3478880
Appears to affect all methods of emerald eggs only

![](https://cdn.discordapp.com/attachments/537784151970021376/905969264903749682/unknown.png)

To reproduce: search with any params in the Emerald Egg generator

**Comment by Real96** [comment]
Commit d892099 broke it
