### ISSUE TITLE
Gen 8 Egg Profile Manager not allowing selection of saved profiles

### ISSUE THREAD

**Issue by capitalism-sudo** [Admiral-Fish/PokeFinder#204]
I have created a profile, using my TID (which is added as the max for some reason) and SID, and checking shiny charm. I see that it is saved in the profile.json in the directory that I chose, but I cannot select it in the profile manager. Is this not something important to the eggs?

**Comment by Admiral-Fish** [comment]
Can't reproduce. Make sure to select either "Brilliant Diamond" or "Shining Pearl" for game version.

**Comment by SteveCookTU** [comment]
I have been able to reproduce the issue. Restarting the pokefinder will allow the profile to display. Will work on a fix for actively refreshing the profile list.
