### ISSUE TITLE
[Gen 6+] IV Calculator Characteristics for G6+ are outdated

### ISSUE THREAD

**Issue by Lincoln-LM** [Admiral-Fish/PokeFinder#221]
The characteristics in IV Calculator remain the ones from before gen 6 even when selecting a gen 8 game. As seen [here](https://bulbapedia.bulbagarden.net/wiki/Characteristic), two of the HP characteristics' text changed for gen 6+ games.

**Comment by Admiral-Fish** [comment]
Does this only matter for English? According to that article it was a mistranslations

**Comment by Lincoln-LM** [comment]
In other languages characteristics can also vary between generations. I think the variation otherwise is slight instead of being the completely wrong characteristic like it is in English, so it depends if its planned to have it match the characteristic text exactly or not.

**Comment by Admiral-Fish** [comment]
I don't want to deal with differing characteristics. I think just choosing one or the other would be best
