### ISSUE TITLE
Incorrect encounter slot in gen 3 safari zone in searcher tab

### ISSUE THREAD

**Issue by c-poole** [Admiral-Fish/PokeFinder#247]
If one was to look at the first few frames in the safari zone in the generator tab, the following results appear.
![image](https://user-images.githubusercontent.com/30779673/159741476-7b31054a-8060-48db-87bb-7bae418b9f47.png)

If we were to search for these first few frames in the searcher tab, however, we would get strange results. The PID and IV can be found on the expected seeds, but the encounter slot is different.

![image](https://user-images.githubusercontent.com/30779673/159741924-bea19eb6-4544-41bd-81b2-611df700d7f4.png)

I've done this search a few times and noticed a consistent pattern. Whatever the encounter slot generator reports should appear 1 frame later is the encounter slot the searcher reports. In this case, Advances=1 reports slot 5 and the seed for Advances=0 reports slot 5 in the searcher tab. Separate testing with the PRNG freeze ACE as well as the fact that several people have RNGed targets in the safari zone and been able to find frames they hit in generator suggests that the searcher tab is the one in error.

**Comment by Real96** [comment]
> If one was to look at the first few frames in the safari zone in the generator tab, the following results appear. ![image](https://user-images.githubusercontent.com/30779673/159741476-7b31054a-8060-48db-87bb-7bae418b9f47.png)
> 
> If we were to search for these first few frames in the searcher tab, however, we would get strange results. The PID and IV can be found on the expected seeds, but the encounter slot is different.
> 
> ![image](https://user-images.githubusercontent.com/30779673/159741924-bea19eb6-4544-41bd-81b2-611df700d7f4.png)
> 
> I've done this search a few times and noticed a consistent pattern. Whatever the encounter slot generator reports should appear 1 frame later is the encounter slot the searcher reports. In this case, Advances=1 reports slot 5 and the seed for Advances=0 reports slot 5 in the searcher tab. Separate testing with the PRNG freeze ACE as well as the fact that several people have RNGed targets in the safari zone and been able to find frames they hit in generator suggests that the searcher tab is the one in error.

Safari has been fixed in last commit recently. Can you pls try it and let us know if this is still a thing?

**Comment by Real96** [comment]
Fixed in 25e88b2
