### ISSUE TITLE
My Gen8 Mysthics choice is disappear!!

### ISSUE THREAD

**Issue by Dalk2ness** [Admiral-Fish/PokeFinder#250]
My Gen8 Mysthics choice is disappear and i try to download event but i get some error "make sure you are connect internet and openssl are setup"

**Comment by Admiral-Fish** [comment]
Need reproduction steps. I don't know what you are talking about

**Comment by Real96** [comment]
Not getting this too in last commit

**Comment by Real96** [comment]
Talked to the user, he's not getting this in la test commit
