### ISSUE TITLE
[Gen 8] TID may has 6 digits, but profile's max input digits are 5

### ISSUE THREAD

**Issue by i493052739** [Admiral-Fish/PokeFinder#255]
Location:  at the Wild Gen 8's Profile Manager
Issue: max digits limit of TID is not satisfy the actual TID length, and when adding a new profile of Sword / Shield to the profile manager, the profile will not be shown in the profile list of the 'Wild Gen 8' window.

**Comment by Admiral-Fish** [comment]
Internal calculations of the game still use the 5 digit TID/SID. The new "display" TID has 6 digits. You need to provide the 5 digit TID/SID values

**Comment by i493052739** [comment]
> Internal calculations of the game still use the 5 digit TID/SID. The new "display" TID has 6 digits. You need to provide the 5 digit TID/SID values

thanks!!

**Comment by JaxonGBake** [comment]
Which 5 digits of the Trainer ID should be provided, first 5 or last 5?
