### ISSUE TITLE
[Feature Suggestion] Comparison Operators in Researcher

### ISSUE THREAD

**Issue by Lincoln-LM** [Admiral-Fish/PokeFinder#257]
Implementing comparison operators into researcher (</>/<=/>=/==/!=) would be helpful for things like gen 3 feebas/swarm triggers and gen 4 encounter-on-step calculation. This would allow one to more easily convert the raw numbers into readable values like true/false (1/0 if it has to be represented as a number), and could even be chained together by referencing previous customs.

**Comment by Admiral-Fish** [comment]
Completed in 7660a34
