### ISSUE TITLE
pokefinder wont open on my Mac

### ISSUE THREAD

**Issue by Rovari69** [Admiral-Fish/PokeFinder#260]
as i try to open the pokefinder app i get a message my mac cant verify if there are any malware. so my only option from there is to send it to the trashcan.. hope you can help me out

**Comment by Admiral-Fish** [comment]
The internet if your friend https://news.trendmicro.com/2021/12/16/how-to-fix-macos-cannot-verify-that-this-app-is-free-from-malware-error/
