### ISSUE TITLE
Cannot pull event data for Gen 8 Raid

### ISSUE THREAD

**Issue by Billo-PS** [Admiral-Fish/PokeFinder#263]
## Description:
When attempting to download promotional raid data I am presented with the following error:
_"Make sure you are connected to the internet and have openSSL setup"_ (Image below)

### Local setup:
Latest commit - https://github.com/Admiral-Fish/PokeFinder/commit/c8f6c0505e9f37381638f4cdcaec7a832389b42b
Connected to Wi-Fi
Fresh install of Pokefinder
Windows machine
Windows 10 OS

**Comment by Billo-PS** [comment]
![Pokefinderissue](https://user-images.githubusercontent.com/63661653/184998105-fc8bdeae-2a41-4dfd-b746-6ab7fbfecbcf.png)
Image didn't attach

**Comment by edwarbad23** [comment]
> ## Description:
> When attempting to download promotional raid data I am presented with the following error: _"Make sure you are connected to the internet and have openSSL setup"_ (Image below)
> 
> ### Local setup:
> Latest commit - [c8f6c05](https://github.com/Admiral-Fish/PokeFinder/commit/c8f6c0505e9f37381638f4cdcaec7a832389b42b) Connected to Wi-Fi Fresh install of Pokefinder Windows machine Windows 10 OS

Have same error

**Comment by Admiral-Fish** [comment]
This appears to have been fixed by #289
