### ISSUE TITLE
Unable to view profiles

### ISSUE THREAD

**Issue by UwU1706** [Admiral-Fish/PokeFinder#265]
This is my first time using this programm to bare with me. When I tried to setup my first profile I noticed it wasnt saving and after researching a bit I found out it was a common bug with this programm. I followed most of the advice I saw on here e.g shortening your path and symbols but none of these help. I changed the path to C:\User\Desktop\PokeFinderwindows.
Any help would be appreciated.

**Comment by Real96** [comment]
> This is my first time using this programm to bare with me. When I tried to setup my first profile I noticed it wasnt saving and after researching a bit I found out it was a common bug with this programm. I followed most of the advice I saw on here e.g shortening your path and symbols but none of these help. I changed the path to C:\User\Desktop\PokeFinderwindows. Any help would be appreciated.

Did you try last commit? Download it [here](https://ci.appveyor.com/project/Admiral-Fish/pokefinder/builds/44508709/job/4yv691cjli4tf5pi/artifacts)

**Comment by Real96** [comment]
> This is my first time using this programm to bare with me. When I tried to setup my first profile I noticed it wasnt saving and after researching a bit I found out it was a common bug with this programm. I followed most of the advice I saw on here e.g shortening your path and symbols but none of these help. I changed the path to C:\User\Desktop\PokeFinderwindows. Any help would be appreciated.

any news?

**Comment by Admiral-Fish** [comment]
I have never seen this before. Please ensure your setting for the profiles json is correct.

Reopen with further details if the issue persists.
