### ISSUE TITLE
Profiles deleted

### ISSUE THREAD

**Issue by RentaroArts** [Admiral-Fish/PokeFinder#266]
I just opened Pokefinder today and all of my profiles just disappeared. I looked at the profiles file and it was empty.

**Comment by Real96** [comment]
Did you update pokefinder? If yes, this can be the reason

**Comment by Real96** [comment]
> I just opened Pokefinder today and all of my profiles just disappeared. I looked at the profiles file and it was empty.

any news?

**Comment by Admiral-Fish** [comment]
Have never experienced this before. Please ensure your setting to the profiles json file is correct.

Reopen with further details if issue still persists.
