### ISSUE TITLE
TID is too long for a profile

### ISSUE THREAD

**Issue by RJDoran93** [Admiral-Fish/PokeFinder#276]
Trying to get this working with Brilliant Diamond, but it won't let me make a proper profile for that game. My trainer ID is 920228 and the highest it can go is 65535. This isn't a modded save file. Is the ID No. on the trainer card not what I should be using for the TID? Any help would be appreciated :)

**Comment by Admiral-Fish** [comment]
Duplicate of https://github.com/Admiral-Fish/PokeFinder/issues/255

See that issue for the explanation
