### ISSUE TITLE
Gen 4 IDSearcher max delay limit of 0xe8ffff

### ISSUE THREAD

**Issue by omernaveedxyz** [Admiral-Fish/PokeFinder#281]
I am searching for a specific TID/SID combination (0/0) in gen 4 and it appears that Pokefinder stops searching after a delay of 15269887 (0xe8ffff) is reached. The same was true for RNGReporter. Is there a reason for this? I understand that such as high delay may be unreasonable to ever RNG properly, but knowing that a valid seed exists is still useful.

Edit: Setting that starting delay to 15269887 and the max delay to a very large number seems to work properly. Perhaps consider increasing the top-end value of maxDelay when a user selects "Infinite Search" to something larger?

[Code Referenced](https://github.com/Admiral-Fish/PokeFinder/blob/188371ce1ff6e046fd98081c8d08ddea434fbd89/Source/Core/Gen4/Searchers/IDSearcher4.cpp#L31)

**Comment by Admiral-Fish** [comment]
The range of `ab` and `cd` get us to a max value of 0xff170000, adding 0xe8ffff to this gets us to 0xffffffff which searches the entire possible seed range.

There is no need to increase this value as it would be a waste.

**Comment by Henny022** [comment]
This won't allow you to hit really low starting seed though, right?
Seeds that would require a really low delay that is not possible to hit.
For these you'd need to overflow the initial seed.
If you account for that the highest required delay would be `2^24 + min_delay`.
