### ISSUE TITLE
Dropdown menus appear on wrong monitor

### ISSUE THREAD

**Issue by Henny022** [Admiral-Fish/PokeFinder#282]
Running on a 3 monitor setup, the dropdown menus always appear on my rightmost monitor, regardless of what monitor the actual window is on.
If the main window is on that monitor they appear where they should.
otherwise they appear on the left edge of that rightmost monitor.
This was introduced in the 4.0.1 release (4.0.0 works as intended)

**Comment by Admiral-Fish** [comment]
This is likely an issue with Qt itself. https://bugreports.qt.io/browse/QTCREATORBUG-25471

**Comment by Admiral-Fish** [comment]
https://bugreports.qt.io/browse/QTBUG-106099 seems to be fixed on 6.5.1, I'll close when I update my Qt version
