### ISSUE TITLE
Missing dll Files

### ISSUE THREAD

**Issue by Dusk595** [Admiral-Fish/PokeFinder#286]
I downloaded this program but the dll files are missing. How come?

**Comment by Admiral-Fish** [comment]
This is not enough information. What dll files are missing?

**Comment by Dusk595** [comment]
MSVCR120.DLL  and  VCRUNTIME140.DLL

**Comment by Admiral-Fish** [comment]
This information is included in the release notes.

https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170
