### ISSUE TITLE
Pokefinder not saving colosseum profile

### ISSUE THREAD

**Issue by 8bitmana** [Admiral-Fish/PokeFinder#287]
Hello! I am having an issue where pokefinder wont save my profile when I set the game to colosseum. However when I set the game to any other game such as ruby or sapphire, the profile saves. Any help with this would be much appreciated. thank you!

**Comment by Real96** [comment]
Which PokeFinder build are you using?

**Comment by Admiral-Fish** [comment]
Unable to reproduce
