### ISSUE TITLE
unable to select "Sword" as gen 8 game

### ISSUE THREAD

**Issue by Nytzzzzzzzzz** [Admiral-Fish/PokeFinder#288]
when selecting your gen 8 game as sword, pokefinder interprets it as being a bdsp game, aka swarm and pokeradar are showing up when they shouldn't be

**Comment by Real96** [comment]
Which PokeFinder build are you using?

**Comment by Admiral-Fish** [comment]
Sword is only select-able in the Raid window. Any Sword/Shield profiles won't be shown in Static and Wild
