### ISSUE TITLE
Add Height support for BDSP

### ISSUE THREAD

**Issue by Unknown-Warrior** [Admiral-Fish/PokeFinder#300]
With G8Height==G9Scale and it being a factor in both PLA and SV I think there's merit to add a Height variable to RNG for in BDSP and potentially S/S Raids.

**Comment by Admiral-Fish** [comment]
Is there documentation on what RNG calls this uses?

**Comment by Unknown-Warrior** [comment]
I've been told it's a rand(129)+rand(128) call that occurs right after generating IVs.
Lego has added it to SwSh OWRNG here: https://github.com/LegoFigure11/swsh-overworld-rng-gui/blob/main/SWSH_OWRNG_Generator.Core/Util/Common.cs#L130

BDSP's should (probably?) be the same

**Comment by SteveCookTU** [comment]
For BDSP it is after nature with the same two rand calls for each height and weight

**Comment by Admiral-Fish** [comment]
Fixed in c99d0db
