### ISSUE TITLE
HGSS egg Rng Broken

### ISSUE THREAD

**Issue by stopper4** [Admiral-Fish/PokeFinder#302]
Hello,
i lost hours today trying to rng for an egg, costantly hitting seed and chatot sounds perfectly but getting the wrong IVS.
I went back to the previous version and i got it immediately.
I doube checked then in the latest version and the IV spread was messed up as i thought.
In attachment the proofs

![ffffffffff](https://github.com/Admiral-Fish/PokeFinder/assets/136117400/47abc5b6-97e5-4c3c-8017-5631a0fa77e4)
![eeeeeeeeee](https://github.com/Admiral-Fish/PokeFinder/assets/136117400/977f0817-a3dc-47b7-b1f2-d91052fe8c70)

**Comment by SteveCookTU** [comment]
If this is with the latest release, the issue has been fixed with #301

Try downloading the latest nightly build from AppVeyor and test with that version.

**Comment by stopper4** [comment]
> If this is with the latest release, the issue has been fixed with #301
> 
> Try downloading the latest nightly build from AppVeyor and test with that version.

ok thanks, sorry i didn’t
know about the nightly build. My issue was in the official 4.1.0 release
