### ISSUE TITLE
Searching for generic pokemon causes massive memory usage [Gen 3 Wild]

### ISSUE THREAD

**Issue by parknich081** [Admiral-Fish/PokeFinder#303]
I was trying to find a valid shuppet to hack in with pkhex, and while i was doing that my computer froze and crashed due to a out of memory error. (I have 32GB of ddr4 ram) This happened with Gen 3 wild, i do not know if it happens for others

**Comment by Admiral-Fish** [comment]
I don't support hacking use cases
