### ISSUE TITLE
SoulSilver - Red Gyarados (Shiny + Max Stats?)

### ISSUE THREAD

**Issue by ultenhiemer** [Admiral-Fish/PokeFinder#309]
On Pokefinder using Gen 4 static (Pokemon SoulSilver) for the Red Gyarados from the Lake of Rage, unlike every other pokemon that this is done for... apparently has shiny version(s) with max IV's (As claimed by PokeFinder).

When all the details are accurately put into PKHeX however I get two legality issues (Invalid: Encounter Type PID Mismatch and Invalid: Static Encounter Shiny Mismatch) Gyarados isn't shiny with this information.

So I am wondering if this is an error from Pokefinder?

**Comment by SteveCookTU** [comment]
PokeFinder is to be used for RNG abuse/prediction. We do not provide support for hacking or generating Pokémon with tools such as PKHeX. If you believe there are inaccuracies, please use PokeFinder to RNG the target and provide screenshots of the expected results (PokeFinder) and actual results (Pokémon from in-game).
