### ISSUE TITLE
Pokefinder 4.1.0 incorrect pokemon frames in Emerald underwater route 124 126

### ISSUE THREAD

**Issue by jamesryan1896** [Admiral-Fish/PokeFinder#311]
Hi,
I have used Pokefinder to shiny hunt a number of pokemon so I am 100% sure my SID (8693) and TID (31640) are correct. However, when I attempt to shiny hunt Relicanth underwater I continue to catch Pokemon which are not listed by Pokefinder. For example I just caught a level 20 Chinchou on Route 126 using sweet scent. Its nature is Serious, IV spread is 25-29 (HP), 29-31 (atk), 9-13 (def) , 28-31 (sp. at), 18-22 (sp. df), 11-15 (spd) and this pokemon is not availble in method Wild 2. It is available once at the correct level on Method wild 4, however the previous pokemon I caught in attempting this was only available in Wild 2 , not Wild 4 (I no longer remember the stat spread). I also had this issue in Jagged Pass when attempting to find a shiny Numel. Instead I had to catch my Numel on Route 112.

**Comment by Admiral-Fish** [comment]
This is how Gen 3 works with vblank. There is no reliable way to know if you will hit Method 1/2/4.
