### ISSUE TITLE
Gen 5 TID/SID rng timer0 shown for results with profile set to timer0 range

### ISSUE THREAD

**Issue by NickPlayeZ** [Admiral-Fish/PokeFinder#314]
Can it be changed it so if you put the timer0 in your profile to a range so lets say min 1000 max 1010 that the program spits out which of those timer0s correspond to which of the found results for with gen 5 TID/SID rng.
Would be useful for troubleshooting as this way you gotta manually change the timer0 in your profile each time to 1 of the values from the range until you found what you hit if you wish to know whether the timer0 is whats causing you problems or whether its something else.
Currently just looks like this
![grafik](https://github.com/Admiral-Fish/PokeFinder/assets/80699972/0355b402-1095-4d26-97a7-d479af6c53d2)

**Comment by SteveCookTU** [comment]
Only timer0 min is used for TID calculation in Gen5
