### ISSUE TITLE
Doesn't have the profiles.json archive

### ISSUE THREAD

**Issue by PersonaRandomH** [Admiral-Fish/PokeFinder#315]
I wanted to ask how this work. Every time I read issues when they couldn't save profiles, they actually had profiles.json to choose a path. But when I start PokeFinder, profiles.json doesn't appear anywhere. I don't know if its me that I don't know where to search or its suppose to create that archive. Sorry if my english is not the best.

**Comment by Admiral-Fish** [comment]
It will default to the documents folder if you are using PokeFinder for the first time. Otherwise you will have to look in settings for where it sees the profiles file.
