### ISSUE TITLE
TID/SID does not allow alphanumeric input in order to search matches with PID

### ISSUE THREAD

**Issue by Iristlypie** [Admiral-Fish/PokeFinder#318]
The group field for filters when generating TID/SID combos seems to only allow numeric input, which is fine for inputting desired TIDs or SIDs, but is incompatible with the PIDs as generated in Pokefinder itself, since they also include alphabetical characters. This issue seems to occur in both Gen 3 and Gen 4 TID/SID windows, and potentially Gen 8's, although I personally have no experience with Gen 8 RNG.

**Comment by Admiral-Fish** [comment]
I am unable to reproduce this behavior

**Comment by dillonodonovan** [comment]
The behavior appears to be specific to capitalization. For instance, in the Gen 4 Searcher if I copy a Seed/PID/Hex value to my keyboard and attempt to paste it in the PID filter in the Gen 4 ID filter, the alphabetic characters are not pasted. The same is true if capital alphabet characters are typed into the field, although lowercase alphabetic characters can be typed/pasted without issue.

Mostly a user experience fix to either allow capital alphabet characters to be pasted in the field or to display PIDs from searcher with lowercase alphabetic characters.

**Comment by dillon-odonovan** [comment]
The behavior appears to be specific to capitalization. For instance, in the Gen 4 Searcher if I copy a Seed/PID/Hex value to my keyboard and attempt to paste it in the PID filter in the Gen 4 ID filter, the alphabetic characters are not pasted. The same is true if capital alphabet characters are typed into the field, although lowercase alphabetic characters can be typed/pasted without issue.

Mostly a user experience fix to either allow capital alphabet characters to be pasted in the field or to display PIDs from searcher with lowercase alphabetic characters.
