### ISSUE TITLE
uic: undefined symbol: _ZdlPvm, version Qt_5

### ISSUE THREAD

**Issue by anneranch** [Admiral-Fish/PokeFinder#319]
uic: undefined symbol: _ZdlPvm, version Qt_5

There are many tracks about this error . none actually stating it has been resolved. 

I could use some assistance in actually finding the cause of this error . 
Where to start ?

This is ALL I have :+1: 

/home/nov25-1/.local/bin/qt5-tools uic A.ui
/home/nov25-1/.local/lib/python3.10/site-packages/qt5_applications/Qt/bin/uic: symbol lookup error: /home/nov25-1/.local/lib/python3.10/site-packages/qt5_applications/Qt/bin/uic: undefined symbol: _ZdlPvm, version Qt_5

Process finished with exit code 0

**Comment by Admiral-Fish** [comment]
Pokefinder uses Qt6
