### ISSUE TITLE
Gen 4 PID filter for TID/SID search does not work

### ISSUE THREAD

**Issue by dillon-odonovan** [Admiral-Fish/PokeFinder#320]
When attempting to find a desired seed/PID and using that to filter TID/SID search to find corresponding shiny pairs, I am unable to retrieve any results. Similarly, if I use RNGReporter, I _am_ able to retrieve results.

If I use the TID/SID search and filter on the matching TID found in RNGReporter, and subsequently use the Gen 4 Static Searcher, and update the TID/SID, the results correctly indicate that the PID would be shiny.

I haven't looked through the source yet but is #318 related? Maybe case-sensitive match and thus requiring lowercase alphabetic characters results in no matches?

I really love that PokeFinder is cross-platform and can run it on my Mac, whereas I can't do the same with RNGReporter (ignoring virtualization/emulation options). Would love to see this fixed!

Here are screenshots/scenarios demonstrating the behavior:

<details>
<summary>RNGReporter: Find desired PID (IV/Nature search)</summary>
<img  width="1440" alt="rng-reporter-find-pid" src="https://www.github.com/Admiral-Fish/PokeFinder/assets/39768972/f5d741bb-0f29-45ca-bdfd-a40464e974fb">
</details>

<details>
<summary>PokeFinder: Find desired PID</summary>
<img width="1440" alt="Screenshot 2023-07-31 at 2 43 31 PM" src="https://github.com/Admiral-Fish/PokeFinder/assets/39768972/dc09b0fc-d9ae-4cc7-980a-5abd294d745b">
</details>

<details>
<summary>RNGReporter: Find TID/SID pairs matching PID</summary>
<img  width="1440" alt="rng-reporter-find-tid-for-pid" src="https://github.com/Admiral-Fish/PokeFinder/assets/39768972/f29d2538-660b-4b3f-bf77-6e5248f340c7">
</details>

<details>
<summary>PokeFinder: Find TID/SID pairs matching PID (no results)</summary>
<img width="1440" alt="Screenshot 2023-07-31 at 2 43 40 PM" src="https://github.com/Admiral-Fish/PokeFinder/assets/39768972/463b8932-7dbb-4ab2-8792-c1ddab72806c">
</details>

<details>
<summary>RNGReporter: Seed + TID/SID = Shiny</summary>
<img  width="1440" alt="rng-reporter-shinies-for-seed-and-tid" src="https://github.com/Admiral-Fish/PokeFinder/assets/39768972/ed930556-9102-4549-9550-5e02053bc6a3">
</details>

<details>
<summary>PokeFinder: Seed + TID/SID = Shiny</summary>
<img width="1440" alt="Screenshot 2023-07-31 at 3 10 39 PM" src="https://github.com/Admiral-Fish/PokeFinder/assets/39768972/a58e0eb6-abe7-4eab-93cd-6330681454c4">
</details>

<details>
<summary>PokeFinder: TID filter works to find same TID Seed (can't find this seed when using PID filter)</summary>
<img width="1438" alt="Screenshot 2023-07-31 at 2 48 36 PM" src="https://github.com/Admiral-Fish/PokeFinder/assets/39768972/6246ce4f-a84f-404c-90d3-b75c3a2f92d6">
</details>

**Comment by Admiral-Fish** [comment]
Fixed via https://github.com/Admiral-Fish/PokeFinder/commit/cd4d119fc8eecdb863e3e781682386b1707ddf7f
