### ISSUE TITLE
[Gen4] Wild searcher is inaccurate when using lead abilities

### ISSUE THREAD

**Issue by Real96** [Admiral-Fish/PokeFinder#321]
Generator spreads are correct. Only spread with advances 25 in Searcher is the correct one. Seems like this is due to any lead ability, setting the lead as None, make it work correctly.

Generator:
![image](https://github.com/Admiral-Fish/PokeFinder/assets/20956021/33a2f85f-6687-4206-9443-78105067e3f4)

Searcher:
![image](https://github.com/Admiral-Fish/PokeFinder/assets/20956021/8776d62d-fcc8-40dc-82ba-1f9c14df78dc)

**Comment by Admiral-Fish** [comment]
You have the wrong sync nature selected
