### ISSUE TITLE
[Gen 4] HGSS Safari Zone Old Rod blocks aren't accounted for

### ISSUE THREAD

**Issue by Unknown-Warrior** [Admiral-Fish/PokeFinder#329]
Meadow with 9 waterside blocks: slots 0-1 ought to give Poliwhirl (it does), Finder reports Magikarp

**Comment by Real96** [comment]
Bug confirmed:
![image](https://github.com/Admiral-Fish/PokeFinder/assets/20956021/9e34360c-b8bd-41e3-80ee-bce3db95e9c6)

![image](https://github.com/Admiral-Fish/PokeFinder/assets/20956021/de14ed15-ebd4-4670-8b64-2a0b802f52ae)

Anyway Poliwhirl is correctly showed as ec slot 0, but not as ec slot 1, which in pokefinder is magikarp
