### ISSUE TITLE
[Gen 3] App crashes when advances limits are too high in breeding tab

### ISSUE THREAD

**Issue by Real96** [Admiral-Fish/PokeFinder#330]
The app crashes with the following breeding research setup:

![image](https://github.com/Admiral-Fish/PokeFinder/assets/20956021/dfd3c3b9-da7e-4fab-81ce-dc834fd2e71f)

in release 4.0.0 the crash doesn't happen

**Comment by Admiral-Fish** [comment]
Sounds like a out of memory issue. Limit search range or add filters
