### ISSUE TITLE
Need help for an issue with PokeFinder 

### ISSUE THREAD

**Issue by ZhuSeans** [Admiral-Fish/PokeFinder#340]
I downloaded the new PokeFinder rev 4.1.2, this is my first using,  I met an issue when I open it,  the popup show the issue : Please update path to your profiles file to restore existing profiles ,  but I didn't know how to solve it.  Please help me , thanks.

![屏幕截图 2023-09-23 235922](https://github.com/Admiral-Fish/PokeFinder/assets/145859728/53c6bee3-5af0-4099-a9ce-787e44a77add)

**Comment by Admiral-Fish** [comment]
If you go to Tools -> Settings you should be able to see the location where it has the profiles file. Just verify that path exists.

I just made a change that will auto-create the file on first launch of the program.

**Comment by ZhuSeans** [comment]
Hi administrator (Admiral) ， thanks for your reply.  I am a new user,  and I am not clear how to update this main.cpp into the folder to take effect.  I am not sure that my operation is correct, need your help and thanks~
First, I have already tried to cover this file into the Source folder, but I re-open the Poke Finder .exe still has the same popup.
Can you help me to solve? Thanks so much!!

![1](https://github.com/Admiral-Fish/PokeFinder/assets/145859728/89523d7c-1bb9-4057-98c4-3775a3b943ac)

![2](https://github.com/Admiral-Fish/PokeFinder/assets/145859728/4123cffc-ef2d-4754-a415-6fe30c3f847d)

![3](https://github.com/Admiral-Fish/PokeFinder/assets/145859728/ad5143d0-463f-4572-9d45-9599123d4762)

**Comment by Real96** [comment]
> Hi administrator (Admiral) ， thanks for your reply. I am a new user, and I am not clear how to update this main.cpp into the folder to take effect. I am not sure that my operation is correct, need your help and thanks~ First, I have already tried to cover this file into the Source folder, but I re-open the Poke Finder .exe still has the same popup. Can you help me to solve? Thanks so much!!
> 
> ![1](https://user-images.githubusercontent.com/145859728/270145893-89523d7c-1bb9-4057-98c4-3775a3b943ac.png)
> 
> ![2](https://user-images.githubusercontent.com/145859728/270146018-4123cffc-ef2d-4754-a415-6fe30c3f847d.png)
> 
> ![3](https://user-images.githubusercontent.com/145859728/270146174-ad5143d0-463f-4572-9d45-9599123d4762.png)

You downloaded the source. So what you're doing isn't ok. Just download it from here:
https://ci.appveyor.com/project/Admiral-Fish/pokefinder/builds/48110432/job/wyn351p6pymd67ho/artifacts

**Comment by Admiral-Fish** [comment]
Should also have been fixed by ba2c70

Can test using a nightly build from appveyor
