### ISSUE TITLE
Is it possible to know which pokemon are on which grass tile on any given frame / seed

### ISSUE THREAD

**Issue by obnoxiousish** [Admiral-Fish/PokeFinder#342]
Say for example I want to encounter a Abra reliably on Route 116 by walking into the grass

How could I find out which frames i could enter the grass and encounter abra, in theory Abra should at some point exist on every grass tile in route 116 but no idea how to find specific frame to grass tile data

Considering that the source code? or decompilation version of the source code of emerald exists in theory it should be able to generate this information but I definitely wouldn't be able to code it myself if it doesn't already exists but if it does please let me know how to do it or the software I need to

**Comment by Admiral-Fish** [comment]
https://github.com/pret/pokeemerald/blob/master/src/wild_encounter.c#L502

This will limit what spreads are available since it is a rand call for the encounter instead of sweet scent. I recommend that you just use sweet scent.
