### ISSUE TITLE
[BDSP] Egg Star/Square shininess is reported incorrectly

### ISSUE THREAD

**Issue by Lincoln-LM** [Admiral-Fish/PokeFinder#343]
https://github.com/Admiral-Fish/PokeFinder/blob/178ea34c53171b47d487ea76e0cfcd720229e7ec/Source/Core/Gen8/Generators/EggGenerator8.cpp#L192C1-L197C128

``shiny`` in EggGeneratorState is set to a boolean (0 or 1) rather than 0/1/2 to account for square shininess. it seems like like ``Utilities::getShiny`` was meant to be used like what was done here:

https://github.com/Admiral-Fish/PokeFinder/blob/178ea34c53171b47d487ea76e0cfcd720229e7ec/Source/Core/Gen4/Generators/EggGenerator4.cpp#L174C14-L174C14

**Comment by SteveCookTU** [comment]
Complete in #344
