### ISSUE TITLE
Gen 3 Roamer's Situation

### ISSUE THREAD

**Issue by BurstZen** [Admiral-Fish/PokeFinder#346]
I was playing Pokémon Sapphire and I was trying to catch a shiny Latias, using PokéFinder and the method defined by im a blisy ._. in [this video](https://www.youtube.com/watch?v=FXZ8D0actz4). The first issue I ran into was that PokéFinder doesn't seem to have a way to select roamers in Gen 3. After realizing this, I caught Latias normally and then calculated the IVs on a separate website ([this one](https://pycosites.com/pkmn/ivcalc.php)) then tried to find the IVs correlated to the frame that I landed on when I caught Latias. The next problem was that after discussing this with a member of the Blisys Retail RNG Help Discord server, I discovered that the roamers' IVs in Ruby and Sapphire are bugged, resulting in their IVs always generating as 0 across the board except for HP, making it extraordinarily difficult to use PokéFinder to RNG manipulate roamers in Ruby and Sapphire. To my knowledge, Pokémon Emerald does not have this issue and the IVs in that game generate just fine. Here are some snippets from the conversation I had on the Discord regarding this problem:

![Discord Screenshot](https://github.com/Admiral-Fish/PokeFinder/assets/149140386/60aa9201-21d3-4408-bc87-366b652511cb)

**Comment by Real96** [comment]
Latios/Latias you see in PokeFinder are the stationaries encounters, not roamers. We all know about the ivs bug. But eon ticket latios/latias are not affected by this
