### ISSUE TITLE
Inaccurate Wild Seeds/Times for Shiny (HGSS)

### ISSUE THREAD

**Issue by carpenc1234** [Admiral-Fish/PokeFinder#357]
Hunting for a Larvitar @ Mt. Silver Cave (Upper Mountainside). PokeFinder gives me a few seeds to choose from.

- Confirm I'm on the correct seed and time with Irwin calls
- Confirm I'm on the correct advance using Chatot cries
- Hit the Pokemon I'm after, but it's not shiny, the Characteristic is wrong, and the nature is wrong

I've repeated this for 4 different seeds for this Larvitar. This seems to be a bug with PokeFinder unfortunately.

Attaching screenshot which has all the info needed to repro this issue (SID/TID, Location, and SEED). The seeds have been very simple to hit if you're trying to repro (btw advance starts around frame 20 on the snowy mountainside I'm on).

![Soul Silver Larvitar RNG](https://github.com/Admiral-Fish/PokeFinder/assets/66259963/881e4420-a6fd-41c6-bcfe-83af23471979)

**Comment by SteveCookTU** [comment]
The PID will rely on the nature during the re-roll part of the generation which that being incorrect tells me there may be an issue particular to nature if IVs are correct. Any chance you have a synchronize lead? Usually a different lead than what is entered in PokeFinder can cause most issues.

**Comment by carpenc1234** [comment]
Don't have that poke on me or any of the others (master ball'd them and checked natures / characteristics so I didn't save obvi). 

The encounter is the right pokemon, but wrong nature and characteristics. Also, no Cute Charm or Synchro lead

**Comment by carpenc1234** [comment]
5th and 6th time's the charm: Shiny Larvitar Hunted x2 (Confirmed stats, nature, gender, and characteristic)

I got the first one after a few minutes and saw that it was shiny. This confused me because the first 4 times I tried they weren't. I wanted to repro one of the seeds that was_not_ working though, to assist with this issue. But, I hit a shiny (again) on the 6th try. Here's the screenshot for the last seed that I hit, which was shiny and IVs/nature confirmed.


![Soul Silver Larvitar Correct Frame](https://github.com/Admiral-Fish/PokeFinder/assets/66259963/d6ca7517-254e-448d-a0c3-8591cd32d505)

**Comment by SteveCookTU** [comment]
Were you able to confirm the IVs on the first 4 seeds to make sure you did hit the exact frame? Only the encounter being correct wouldn't be enough to confirm it is the correct frame even if on emulator.

**Comment by carpenc1234** [comment]
I wasn't able to confirm IVs on the failed tests :( We can close and I'll be sure to link this issue if I see it again.

**Comment by cervizzz** [comment]
Did your lead have pressure, hustle or vital spirit, perchance?

Also, your SID is wrong. It should be 39765.

**Comment by Admiral-Fish** [comment]
Feel free to open another issue with additional information if you encounter this issue again
