### ISSUE TITLE
Channel Jirachi Seed Finding Issue in 4.1.2

### ISSUE THREAD

**Issue by zak-shwap** [Admiral-Fish/PokeFinder#361]
Issue lies the Seed Value that generates. After loading versions previous to 4.1.2, it was found that Seed Values were no longer accurate. 

TEST for Compare = Version 4.0.0
Open Tool > Gen 3 > Game Cube > Search > Method = Channel > Input Value Spread \/ > Shiny = Square/Star 

HP 21 - 29
Atk 16 -22
Def 12 - 21
SpA 0 - 3
SpD 0 - 3
Spe 10 - 13

Vers 4.0.0

Seed	         PID	             Shiny  Natur               HP	Atk	Def	SpA	SpD	Spe	Hidden	Power	
3E33CA89	A81D5257	Star	Hasty	1	28	17	15	2	0	12	Flying	42	-
F935FE39 	3170CB7E	Star	Timid	0	21	18	19	1	1	11	Dragon	38	-
9B937666	E0D8C072	Star	Lonely	0	24	22	15	0	2	12	Fighting	54	-
511B2C76	2C547AEC	Star	Gentle	0	28	19	13	0	2	10	Flying	56	-
339EA17A	5E6CAE4C	Star	Serious	0	29	22	21	3	3	13	Dragon	61	-

Compare to Update 4.1.2 same parameters spread and input direct.

Seed	         PID	             Shiny  Nature	    Ability	                HP	Atk	Def	SpA	SpD	Spe	Hidden	Power	
98BBC6FB	A81D5257	Star	Hasty	1: Serene Grace	28	17	15	2	0	12	Flying	42	-
C2FB63FD	3170CB7E	Star	Timid	0: Serene Grace	21	18	19	1	1	11	Dragon	38	-
48670580	E0D8C072	Star	Lonely	0: Serene Grace	24	22	15	0	2	12	Fighting	54	-
84C35810	2C547AEC	Star	Gentle	0: Serene Grace	28	19	13	0	2	10	Flying	56	-
A8CD4138	5E6CAE4C	Star	Serious	0: Serene Grace	29	22	21	3	3	13	Dragon	61	-

This creates inaccurate instances for RNG manip and hunt.

**Comment by zak-shwap** [comment]
https://www.youtube.com/watch?v=e2hGP30Dge8&t=74s

Spreads were based on Im_blisy video in which Shiny was obtained

**Comment by Lincoln-LM** [comment]
The seed's position in channel jirachi's generation sequence was changed to match the generator tab. All spreads produced should still be valid (as your example seems to imply), the seed given just refers to the RNG state you need to be on on the menu prior to generating jirachi, rather than being the rng state as the jirachi generates. Tools like Jirachi Advancer would need to be updated if they want to match this but it shouldn't be generating anything inaccurate as is.

**Comment by Real96** [comment]
> The seed's position in channel jirachi's generation sequence was changed to match the generator tab. All spreads produced should still be valid (as your example seems to imply), the seed given just refers to the RNG state you need to be on on the menu prior to generating jirachi, rather than being the rng state as the jirachi generates. Tools like Jirachi Advancer would need to be updated if they want to match this but it shouldn't be generating anything inaccurate as is.

I think that atm Pokefinder is wrong as the user said. Both searcher and generator.

This is latest pokefinder commit:
![image](https://github.com/Admiral-Fish/PokeFinder/assets/20956021/7d8ee73b-8d45-47f2-a560-aa8cfdd48467)
![image](https://github.com/Admiral-Fish/PokeFinder/assets/20956021/37533582-223a-4ac8-aafb-cd738926504c)

This is how i got the spread instead:
![image](https://github.com/Admiral-Fish/PokeFinder/assets/20956021/da2d7886-ef26-4f97-94e8-dbe0b34912b0)
![image](https://github.com/Admiral-Fish/PokeFinder/assets/20956021/451fc9d7-4322-46e0-99c8-f9f6c85a0d03)

Pokefinder says seed 2DBF1CEC and advances 39, 40 and 41. To get the spread i was in the menu at seed 5B60516A advances 46, while at the jirachi generation seed D8D56A1B advances 53. Pokefinder is not accurate rn

**Comment by Real96** [comment]
Added a reference to this issue in #363. I think this can be closed, since Pokefinder calculates seeds and spreads correctly. We just need a path calculator to match its generation
