### ISSUE TITLE
Keeps not responding soon after opening.

### ISSUE THREAD

**Issue by PokeIonYT** [Admiral-Fish/PokeFinder#362]
After I try to do ctrl+c on the id, it suddenly stops responding. I am on Windows 11.

**Comment by Real96** [comment]
> After I try to do ctrl+c on the id, it suddenly stops responding. I am on Windows 11.

Are you using latest commit?

**Comment by PokeIonYT** [comment]
> > After I try to do ctrl+c on the id, it suddenly stops responding. I am on Windows 11.
> 
> Are you using latest commit?

I am using the latest version, using gen 4 tools.

**Comment by Real96** [comment]
> > > After I try to do ctrl+c on the id, it suddenly stops responding. I am on Windows 11.
> > 
> > 
> > Are you using latest commit?
> 
> I am using the latest version, using gen 4 tools.

Try this and tell us if the problem if there too

**Comment by PokeIonYT** [comment]
It still seems to be there.

**Comment by PokeIonYT** [comment]
It doesn't seem to happen on gen 3 tools.

**Comment by Real96** [comment]
> Anyway that it could be fixed that you know of?

do you press Ctrl+C here? Cause it isn't giving me any problems
![image](https://github.com/Admiral-Fish/PokeFinder/assets/20956021/75dc8188-b526-4824-a9dd-97cfed7dae2c)

**Comment by Admiral-Fish** [comment]
Unable to replicate. Both Ctrl+C and double click copy the text for me without any crashing.

Feel free to reopen if you provide more detail instructions on how to replicate (what window you are using, specific actions taken, etc.).
