### ISSUE TITLE
Nightly Pokefinder's Gen 5 Wild RNG Tab Bugged

### ISSUE THREAD

**Issue by SephiraZafkiel** [Admiral-Fish/PokeFinder#364]
![Gen 5 Wild RNG 1](https://github.com/Admiral-Fish/PokeFinder/assets/99696373/3c579331-9a5b-4a1a-b07a-cf88a05bbc5a)
![Gen 5 Wild RNG 2](https://github.com/Admiral-Fish/PokeFinder/assets/99696373/bf8396ac-e6ae-4568-a7bf-2e26ebd82255)

In the above images I've compared Bambo's Fork of RNGReporter for Gen 5 Wild and the Nightly Build for Gen 5 Wild RNG of Pokefinder. I presume when searching every year that it'll go in order in the Generator (.eg 2000 > 2001) but when I correctly did my RNG manip it was with Bambo's Fork of RNGReporter that happened to be in 2024 while Gen 5 Pokefinder did not show up with that spread instead for a bugged 2025 spread. If you may fix this please, and let me know if you need more info. Thank you in advance!

**Comment by Real96** [comment]
> ![Gen 5 Wild RNG 1](https://private-user-images.githubusercontent.com/99696373/301908094-3c579331-9a5b-4a1a-b07a-cf88a05bbc5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1Mjc0NzEsIm5iZiI6MTcyOTUyNzE3MSwicGF0aCI6Ii85OTY5NjM3My8zMDE5MDgwOTQtM2M1NzkzMzEtOWE1Yi00YTFhLWIwN2EtY2Y4OGEwNWJiYzVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE2MTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwOTAzNmY5MDE4ODliNjI1MTc3OGMxNTQ5NWFiNDdkNWQxMGY5MDgwZWQ1MmI2YmIyMGRkYTkxNzcyYjVkZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W54ypHwNB-asXvnq7OBfmL67L6pFKkkQuJHKJNa_wzE) ![Gen 5 Wild RNG 2](https://private-user-images.githubusercontent.com/99696373/301908120-bf8396ac-e6ae-4568-a7bf-2e26ebd82255.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1Mjc0NzEsIm5iZiI6MTcyOTUyNzE3MSwicGF0aCI6Ii85OTY5NjM3My8zMDE5MDgxMjAtYmY4Mzk2YWMtZTZhZS00NTY4LWE3YmYtMmUyNmViZDgyMjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE2MTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZDBkMzYwMzgzZWI0NmNiMTI0MjU2NjAzMzU1Nzk4ZjNjNzhhMzdkMDEyYzEwODYyY2FkNzVkYzA2MGZjZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1KvITEvF5sB51spFtHxoGkeggtAtDxyy8pQ5cc-nHSs)
> 
> In the above images I've compared Bambo's Fork of RNGReporter for Gen 5 Wild and the Nightly Build for Gen 5 Wild RNG of Pokefinder. I presume when searching every year that it'll go in order in the Generator (.eg 2000 > 2001) but when I correctly did my RNG manip it was with Bambo's Fork of RNGReporter that happened to be in 2024 while Gen 5 Pokefinder did not show up with that spread instead for a bugged 2025 spread. If you may fix this please, and let me know if you need more info. Thank you in advance!

![image](https://github.com/user-attachments/assets/9e8c889b-4ebd-4560-8759-fcd96d0b2000)

PokeFinder finds correctly the spread you found in the forked rngreporter. So i think this issue can be closed.
