### ISSUE TITLE
Voltorb and Roamer missing from Gen 3 Static

### ISSUE THREAD

**Issue by RetailRNG** [Admiral-Fish/PokeFinder#366]
There are several level 25 Voltorbs available in New Mauville in Gen 3, it should be added in the "Stationary" category of Gen 3 Static with Electrode, Kecleon, and Sudowoodo. It is in both Ruby & Sapphire, and Emerald. 

There is also no Roamers for any of the Gen 3 games. They should be their own **Category**, even Latios and Latias, because they are level 40 instead of 50 like Southern Island, and they have different (bugged) generation in R/S

**Comment by firestar300** [comment]
+1
