### ISSUE TITLE
Lotad Missing from Gen 3 Emerald spawn Points Near Route 114, 102, etc.

### ISSUE THREAD

**Issue by erxx** [Admiral-Fish/PokeFinder#371]
As described, Lotad is missing from the drop down list in Gen 3 Emerald - Wild - Grass - Route 102 and 114. 

Potentially other spawns missing as well.

**Comment by Admiral-Fish** [comment]
Unable to reproduce

![image](https://github.com/Admiral-Fish/PokeFinder/assets/24730718/27d518ad-116b-4023-bed3-2c2bdfd738f5)

![image](https://github.com/Admiral-Fish/PokeFinder/assets/24730718/7e872502-dbcf-462f-9ef8-4c3c37f2862f)
