### ISSUE TITLE
Gen 3 Wild - Emerald - PIDs not shiny

### ISSUE THREAD

**Issue by erxx** [Admiral-Fish/PokeFinder#372]
When looking in Gen 3 Wild for a Swablu on Route 114, all Methods return PIDs but they are not recognised as shiny .e.g in pkHex

**Comment by erxx** [comment]
Update: This is also true for Shuppet

**Comment by erxx** [comment]
Same for Spheal apparently. Although I managed to get a shiny one a few days back but I am unsure how I did it and if I did it with PokeFinder.

**Comment by erxx** [comment]
Same for Ditto

**Comment by erxx** [comment]
Same for Lotad

**Comment by Admiral-Fish** [comment]
Please provide examples (screenshots or PID and TID/SID information)

**Comment by erxx** [comment]
for example these dittos are not shiny.. 
![image](https://github.com/Admiral-Fish/PokeFinder/assets/715342/f9775762-2871-4e04-b44d-6545ca4ad31d)

**Comment by erxx** [comment]
Same for Manaphy 

![image](https://github.com/Admiral-Fish/PokeFinder/assets/715342/602464a0-1228-4012-80c0-ab8f9dc1adb9)

**Comment by erxx** [comment]
same for Ditto 
![image](https://github.com/Admiral-Fish/PokeFinder/assets/715342/e3791357-1c6c-4f3f-a227-c884cc8c811c)

**Comment by erxx** [comment]
Same for Dunsparce
![image](https://github.com/Admiral-Fish/PokeFinder/assets/715342/52a06ae1-a2c0-4cf5-bd82-4ef6fc2112b2)

**Comment by Admiral-Fish** [comment]
If pokefinder were giving incorrect shiny results I think I would have heard about it from more people. Likely you have the wrong TID/SID. You mentioned it being wrong in pkhex, do you a pkm file you could upload here for analysis.

**Comment by Real96** [comment]
Tested all the PIDs showed above with the IDs. All are shown as shiny in Pokefinder, i'm closing this. In case you provide a valid pk file with this bug, we will reopen the issue.
