### ISSUE TITLE
Spheal missing from Route 125 on Gen 3 Wild - Emerald

### ISSUE THREAD

**Issue by erxx** [Admiral-Fish/PokeFinder#373]
According to the internet, Spheal can also appear on Route 125 but is not included in the Gen 3 Wild - Emerald Location dropdown menu.

**Comment by Admiral-Fish** [comment]
Please provide a source, according to Bulbapedia and my encounter dumps from the game this is incorrect

![image](https://github.com/Admiral-Fish/PokeFinder/assets/24730718/31e34af6-b595-4b20-999d-c2ed9643f13f)
