### ISSUE TITLE
PIDs from Gen 3 Static for Squirtle are not Shiny even when it says so

### ISSUE THREAD

**Issue by erxx** [Admiral-Fish/PokeFinder#374]
As described above neither Method 1 nor Method 4 provides PIDs which are recognised as shiny by PKHex

**Comment by Admiral-Fish** [comment]
Please provide examples (screenshots or PID and TID/SID information)

**Comment by Admiral-Fish** [comment]
Closing as duplicate of #372

Nothing different about shiny determination between static and wild encounters
