### ISSUE TITLE
Battle Frontier not available as Encounter location

### ISSUE THREAD

**Issue by erxx** [Admiral-Fish/PokeFinder#375]
![image](https://github.com/Admiral-Fish/PokeFinder/assets/715342/53b7c3fc-03a7-4949-bfa3-e91d9fd07ce7)
Sudowoodo can be found here after beating the game and has Battle Frontier as met location in the Dex. It should be added.

**Comment by Admiral-Fish** [comment]
It's under static encounters

![image](https://github.com/Admiral-Fish/PokeFinder/assets/24730718/c709bbec-125d-40d3-ae66-a2870455ca87)
