### ISSUE TITLE
Gen 8 Profile won't show up

### ISSUE THREAD

**Issue by keebo98** [Admiral-Fish/PokeFinder#379]
![Screenshot (178)](https://github.com/Admiral-Fish/PokeFinder/assets/165685703/a7cf462a-edd4-4111-b4d9-d16b6873de64)
The Profile for Gen 8 won't show up...

**Comment by Admiral-Fish** [comment]
I don't see what the issue is. You have to select your desired profile in the drop down in the Gen 8 Wild window

**Comment by keebo98** [comment]
The profile won't show up for Sword or Shield game but would show up for BDSP
![Screenshot (179)](https://github.com/Admiral-Fish/PokeFinder/assets/165685703/7909863f-ae75-4834-a938-a2ac7edc6e9f)

**Comment by keebo98** [comment]
This is a better view to explain it 
![Screenshot (180)](https://github.com/Admiral-Fish/PokeFinder/assets/165685703/e4d92ce4-4898-4b21-b9c4-5b59349bf987)
![Screenshot (181)](https://github.com/Admiral-Fish/PokeFinder/assets/165685703/206b0d8e-10ba-476f-afb4-8c094f8b782e)

**Comment by Admiral-Fish** [comment]
Oh the only thing supported currently for Sword/Shield is raids
