### ISSUE TITLE
DPPt Maniac Tunnel Slot issue

### ISSUE THREAD

**Issue by NickPlayeZ** [Admiral-Fish/PokeFinder#380]
Currently if you select the Maniac Tunnel for Wild RNG and want a Hippopotas, Pokefinder auto selects slots 5, 7, 9 and 11 however the slots of Hippo depend on how many Unown you have caught. With 0-9 Unown Hippo only occupies slots 9 and 11. With 10-25 Unown slot 7 gets added and with all 26 Unown slot 5 gets added as well. So imo the location should by default have only slots 9 and 11 selected as I feel most people won't have many Unown caught anyways. Might be useful to add 2 more Maniac Tunnel locations that each account for one extra Hippo slot like "Maniac Tunnel [10-25 Unown]". Geodude slots are also affected ofc as Hippos later slots 5 and 7 are Geodude slots at first.

![grafik](https://github.com/Admiral-Fish/PokeFinder/assets/80699972/86a8dc56-abff-43d6-9db7-58e2b9ad7b51)

**Comment by Admiral-Fish** [comment]
https://bulbapedia.bulbagarden.net/wiki/Maniac_Tunnel

When you hit 26 unowns you would select Maniac Tunnel
