### ISSUE TITLE
Drop down menu bug on Windows

### ISSUE THREAD

**Issue by Jakeysp** [Admiral-Fish/PokeFinder#386]
Latest release has a bug on Windows 11 where the window always opens at the inner edge of the secondary monitor. If you drag the window to your primary monitor, the drop down menu always opens adjacent to it but still at the inner edge of the secondary monitor. See screenshot for what I mean.

Tried running in compatibility mode for Win8 and running as admin, issue persists. Issue does not occur if I leave the application window on the secondary, all behaves as normal as long as I don't try to move PokeFinder to my primary monitor.
![Screenshot](https://github.com/Admiral-Fish/PokeFinder/assets/9799503/2e7639ee-10a6-4b7e-be97-ad0e9cedca50)

**Comment by Real96** [comment]
> Latest release has a bug on Windows 11 where the window always opens at the inner edge of the secondary monitor. If you drag the window to your primary monitor, the drop down menu always opens adjacent to it but still at the inner edge of the secondary monitor. See screenshot for what I mean.
> 
> Tried running in compatibility mode for Win8 and running as admin, issue persists. Issue does not occur if I leave the application window on the secondary, all behaves as normal as long as I don't try to move PokeFinder to my primary monitor.

Can you pls try [latest commit](https://ci.appveyor.com/project/Admiral-Fish/pokefinder/builds/49741155/job/yarkw9icicwqixi6/artifacts) and tell us if the problem is still there?

**Comment by Jakeysp** [comment]
Nope, problem no longer occurs in that build. Nice work, thanks!
