### ISSUE TITLE
Allow the Calibration section of Gen 4 Seed to Time window to show more than 59 seconds

### ISSUE THREAD

**Issue by SexyMalasada** [Admiral-Fish/PokeFinder#401]
Hello!
This is mostly a suggestion and not an issue _per se_, but something older versions of PF allowed, was to show as many entries as you wanted in the Calibration section, by not limiting the -/+ seconds to 59 (as is the case in the latest stable release).
This 'feature' was present in 3.x versions of PF (and maybe in some older 4.x too? I haven't checked those tbh - example picture on a 3.x version below), and while seemingly insignificant, it's somewhat important/makes life easier for those RNGing on emulator platforms that have their own RTC and where you can't freeze time such as BizHawk (ie unlike Desmume + RunAsDate allows you to do).

![image](https://github.com/Admiral-Fish/PokeFinder/assets/104528536/e95df2a7-69e4-42a0-8c05-ba5addbe5708)

Because you can't freeze time with BizHawk for example, you need to treat the RNG part of getting your Initial Seed and hitting your delay much like you would on a retail RNG. By allowing users to input as many -seconds as they wish, this makes it easier to visualize what HH:MM:SS you'd have to input in the RTC, in order to hit your Delay _at_ the required clock time!
- Is this a bit of a 'for lazy people' feature? yes
- Are there many tools or calculators online that could do this for you? yes
Still I believe it's best to have this small feature 'integrated' into PF itself, especially considering it was already present in the app before!
Thanks!

**Comment by Admiral-Fish** [comment]
What kind of allowable range do you think would be realistic?

**Comment by SexyMalasada** [comment]
> What kind of allowable range do you think would be realistic?

Hiya!

Thank you for considering my suggestion!

500 seconds is a value that imo would leave more than enough buffer for this (since it roughly translates to 30,000 Delay), something thereabouts would be my suggestion!
In my own RNG experience with BizHawk I don't think I've **ever** used a value larger than ~300 so far.
