### ISSUE TITLE
When using the Gen 8 Static feature, the Pokemon list is incomplete.

### ISSUE THREAD

**Issue by WINDYHILL-E** [Admiral-Fish/PokeFinder#402]
When using the Gen 8 Static feature in the latest version, the Pokemon list is incomplete.

<img width="933" alt="截屏2024-06-24 22 47 58" src="https://github.com/Admiral-Fish/PokeFinder/assets/40812301/eb3b2869-db28-4bb9-9162-349d4ce09ce2">

**Comment by Real96** [comment]
> When using the Gen 8 Static feature in the latest version, the Pokemon list is incomplete.
> 
> <img alt="截屏2024-06-24 22 47 58" width="933" src="https://private-user-images.githubusercontent.com/40812301/342389876-eb3b2869-db28-4bb9-9162-349d4ce09ce2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTk4MjIsIm5iZiI6MTcxOTg5OTUyMiwicGF0aCI6Ii80MDgxMjMwMS8zNDIzODk4NzYtZWIzYjI4NjktZGIyOC00YmI5LTkxNjItMzQ5ZDRjZTA5Y2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA1NTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzOGIxMWU4NjY4NGRlNGM0NzM4ZTk3NjViOWMwMmI2ZjQ2YTU4MTA3ZGNlMTA1M2E1MWIzZGVmZTgxMDQ3N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f_4UdK1hpkvk5vrPzPT_zKBHiVUQgDgpKMmztolaYv8">

Can you try latest [commit](https://github.com/Admiral-Fish/PokeFinder/actions/runs/9558929227) pls? Let us know if the error is still there

**Comment by WINDYHILL-E** [comment]
> > When using the Gen 8 Static feature in the latest version, the Pokemon list is incomplete.
> > <img alt="截屏2024-06-24 22 47 58" width="933" src="https://private-user-images.githubusercontent.com/40812301/342389876-eb3b2869-db28-4bb9-9162-349d4ce09ce2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTk4MjIsIm5iZiI6MTcxOTg5OTUyMiwicGF0aCI6Ii80MDgxMjMwMS8zNDIzODk4NzYtZWIzYjI4NjktZGIyOC00YmI5LTkxNjItMzQ5ZDRjZTA5Y2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA1NTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzOGIxMWU4NjY4NGRlNGM0NzM4ZTk3NjViOWMwMmI2ZjQ2YTU4MTA3ZGNlMTA1M2E1MWIzZGVmZTgxMDQ3N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f_4UdK1hpkvk5vrPzPT_zKBHiVUQgDgpKMmztolaYv8">
> 
> Can you try latest [commit](https://github.com/Admiral-Fish/PokeFinder/actions/runs/9558929227) pls? Let us know if the error is still there

How should I use the latest commit? I haven't used C++ before, so I'm not very familiar with the build steps.

**Comment by Real96** [comment]
> > > When using the Gen 8 Static feature in the latest version, the Pokemon list is incomplete.
> > > <img alt="截屏2024-06-24 22 47 58" width="933" src="https://private-user-images.githubusercontent.com/40812301/342389876-eb3b2869-db28-4bb9-9162-349d4ce09ce2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTk4MjIsIm5iZiI6MTcxOTg5OTUyMiwicGF0aCI6Ii80MDgxMjMwMS8zNDIzODk4NzYtZWIzYjI4NjktZGIyOC00YmI5LTkxNjItMzQ5ZDRjZTA5Y2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA1NTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzOGIxMWU4NjY4NGRlNGM0NzM4ZTk3NjViOWMwMmI2ZjQ2YTU4MTA3ZGNlMTA1M2E1MWIzZGVmZTgxMDQ3N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f_4UdK1hpkvk5vrPzPT_zKBHiVUQgDgpKMmztolaYv8">
> > 
> > 
> > Can you try latest [commit](https://github.com/Admiral-Fish/PokeFinder/actions/runs/9558929227) pls? Let us know if the error is still there
> 
> How should I use the latest commit? I haven't used C++ before, so I'm not very familiar with the build steps.

The is just in the link i sent you
![image](https://github.com/Admiral-Fish/PokeFinder/assets/20956021/5a54dabd-4a20-4406-9a12-a24a503071e4)

**Comment by WINDYHILL-E** [comment]
It works fine now. Thank you😊

> > > > When using the Gen 8 Static feature in the latest version, the Pokemon list is incomplete.
> > > > <img alt="截屏2024-06-24 22 47 58" width="933" src="https://private-user-images.githubusercontent.com/40812301/342389876-eb3b2869-db28-4bb9-9162-349d4ce09ce2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTk4MjIsIm5iZiI6MTcxOTg5OTUyMiwicGF0aCI6Ii80MDgxMjMwMS8zNDIzODk4NzYtZWIzYjI4NjktZGIyOC00YmI5LTkxNjItMzQ5ZDRjZTA5Y2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA1NTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzOGIxMWU4NjY4NGRlNGM0NzM4ZTk3NjViOWMwMmI2ZjQ2YTU4MTA3ZGNlMTA1M2E1MWIzZGVmZTgxMDQ3N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f_4UdK1hpkvk5vrPzPT_zKBHiVUQgDgpKMmztolaYv8">
> > > 
> > > 
> > > Can you try latest [commit](https://github.com/Admiral-Fish/PokeFinder/actions/runs/9558929227) pls? Let us know if the error is still there
> > 
> > 
> > How should I use the latest commit? I haven't used C++ before, so I'm not very familiar with the build steps.
> 
> I gave you the link to download it: https://github.com/Admiral-Fish/PokeFinder/actions/runs/9558929227
> 
> ![image](https://private-user-images.githubusercontent.com/20956021/345162397-5a54dabd-4a20-4406-9a12-a24a503071e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODE0MjEsIm5iZiI6MTcxOTk4MTEyMSwicGF0aCI6Ii8yMDk1NjAyMS8zNDUxNjIzOTctNWE1NGRhYmQtNGEyMC00NDA2LTlhMTItYTI0YTUwMzA3MWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA0MzIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNWU5ZWUxN2U5M2NmYTI2OTJjNTUwNTQ1ZGEwNmQ0MmU1NzFkM2E2NWM2MDM0ZTlkMmU2MGY2NWFiZmVhOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vvMVeNnM0kS_uWM6EhellTRyYRcfhbQNE-2Tmf18mt4)

It's working perfectly now. Thanks😊
