### ISSUE TITLE
Add support to see Height and Weight when doing Gen 8 Egg RNG

### ISSUE THREAD

**Issue by LordOfOtakus** [Admiral-Fish/PokeFinder#404]
Height and Weight were just recently added for Static Encounters on PokeFinder, the ability to see this for Egg RNG would be very helpful in breeding Jumbo or Teeny Pokémon.

**Comment by Admiral-Fish** [comment]
Through discussion on discord the height/weight is not generated at the same time as breeding. I will not be adding support for this
