### ISSUE TITLE
Initial seed implementation for breeding in Emerald

### ISSUE THREAD

**Issue by ElTerapagosMexicano** [Admiral-Fish/PokeFinder#409]
Hi! Theres a chance for an initial seed implementation in pokefinder for emerald? I was trying to get a spinda with the pid 88888888 on emerald but unfortunately, you need like 10k redraws and initial seed breeding could make this doable.

**Comment by Admiral-Fish** [comment]
After some internal discussion I won't be adding this. Using either battle videos or painting wouldn't be realistic as the calibration value would be near impossible to know on retail
