### ISSUE TITLE
Why can't I open "static" in "gen 8"?

### ISSUE THREAD

**Issue by Dybala-75** [Admiral-Fish/PokeFinder#412]
i have Install the [Microsoft Visual C++ Redistributable](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

**Comment by Dybala-75** [comment]
Version 4.1.2 works fine, so it looks like I need to keep waiting for the next  version

**Comment by Real96** [comment]
> Version 4.1.2 works fine, so it looks like I need to keep waiting for the next version

Known bug already fixed in latest commit. You can get it from here: https://nightly.link/Admiral-Fish/PokeFinder/workflows/windows.yaml/master/PokeFinder-windows.zip
