### ISSUE TITLE
[Gen 5] Current Initial advances are added to intial seed initial advances

### ISSUE THREAD

**Issue by Real96** [Admiral-Fish/PokeFinder#416]
Baically what title says:
![image](https://github.com/user-attachments/assets/89334f5d-efce-4272-9d58-41c615acba3c)
![image](https://github.com/user-attachments/assets/37f3f659-5f6d-4157-b63d-e86025f91034)

In this example, initial advances should be 50. But, instead, they're added to initial seed initial advances which are 46, so it starts from 96 instead of 50.

Windows affected by this:
- Egg
- Event
- Hidden Grotto
- Wild (in gen5 branch)

**Comment by Admiral-Fish** [comment]
This is as intended. The Gen 5 initial advances on boot are always added
