### ISSUE TITLE
Impossible to check nature boxes in dropdown on Linux

### ISSUE THREAD

**Issue by autofire372** [Admiral-Fish/PokeFinder#417]
I can't actually check any of the boxes in the nature dropdown menu with the Linux build. I can do this when running the Windows version in Wine, but that version started crashing Wine all of a sudden when actually generating PIDs.

**Comment by Real96** [comment]
Did you try latest [commit](https://nightly.link/Admiral-Fish/PokeFinder/workflows/windows.yaml/master/PokeFinder-windows.zip)?

**Comment by autofire372** [comment]
The nature dropdown is still bugged on latest commit. The Windows version still crashes Wine on latest commit as well.

**Comment by Admiral-Fish** [comment]
I checked on Ubuntu 24. If you click the area of the box where it shows the text it does like to hide itself right away. You have two options:
1. Click the arrow to the right of the box
2. Click like normal but then don't let go of the mouse until it is hovering over the options below it

My efforts trying to address this have been unsuccessful so far. This behavior is not observable on windows.

**Comment by autofire372** [comment]
This is not fixed. I am still observing the reported behavior with the latest commit.

**Comment by Admiral-Fish** [comment]
I have no idea how to make my new implementation to work. Windows is fine while linux hates it. I am going to revert to the old style. So my original two points will hold for options on using it.

**Comment by autofire372** [comment]
For future reference, this was fixed properly by 99e6ed9.
