### ISSUE TITLE
Remove Gen 4 Generator "Delay" field

### ISSUE THREAD

**Issue by NickPlayeZ** [Admiral-Fish/PokeFinder#418]
I've seen that field be the cause of confusion for dozens of newcomers to RNG manip in the past few months and since there's already an "Initial Advances" field which offers largely the same functionality I don't believe it provides nearly enough value to justify peoples confusion. Or at the very least rename it so no one inputs their target Delay into that field.

**Comment by Admiral-Fish** [comment]
The fields serve fundamentally different purposes. I don't see the benefit in removing it.

**Comment by Real96** [comment]
> The fields serve fundamentally different purposes. I don't see the benefit in removing it.

I think the same, it is necessary. Maybe we can rename it, but removing it would be bad imo

**Comment by NickPlayeZ** [comment]
at least do rename it please yes; cause this way newcomers VERY OFTEN put their target delay in there

**Comment by Real96** [comment]
I can confirm this happens, cause I've seen users new to rng doing this. The only "problem" is that the same box is called delay in the other gens

**Comment by SexyMalasada** [comment]
My 'cheap' way of avoiding this when explaining or teaching RNG to newcomers, is to call the Delay you get when starting an encounter _Delay_, and the Delay from game startup that you target for a given Initial Seed _Delay Frame_; differentiating them clearly.
Maybe calling the latter 'Delay Advancements' on subsequent PF releases?

**Comment by Admiral-Fish** [comment]
Would something like `Offset` make more sense?

**Comment by SexyMalasada** [comment]
> Would something like `Offset` make more sense?

For the first kind (ie delay on encounter), that's actually a great name for it ngl - and keeps the startup counting value still referred as Delay!

**Comment by Real96** [comment]
Something like `Advances Delay` imo would be better

**Comment by SexyMalasada** [comment]
> Something like `Advances Delay` imo would be better

for which of the values though?

**Comment by Real96** [comment]
> > Something like `Advances Delay` imo would be better
> 
> for which of the values though?

`Delay` -> `Advances Delay`

In gen4 generator tab of each rng type

**Comment by SexyMalasada** [comment]
Oh I just remembered another possible option, which would standardize it with 3DSRNGTool!
![image](https://github.com/user-attachments/assets/745e549c-2205-429d-ab1b-244903766926)

But either of the options here sound good to me!

**Comment by NickPlayeZ** [comment]
personally id prefer offset too; something that doesnt include the word "delay" so theres no chance anyone can confuse it
