### ISSUE TITLE
Encounter slot automatic selection is bugged

### ISSUE THREAD

**Issue by Real96** [Admiral-Fish/PokeFinder#422]
When you select a Pokemon in Settings section, the automatic selection of the Encounter Slot in Filters is wrong. The bug happens in gen3 and gen4 and it has been introduced in 82aaca041197970e928f292098e1abb2a7797b1d.

![image](https://github.com/user-attachments/assets/bf74477a-f512-4368-9882-955ecea3f959)
![image](https://github.com/user-attachments/assets/fc72172a-efb0-428c-8d6a-4255e3f1617c)

**Comment by Admiral-Fish** [comment]
[048e3d5](https://github.com/Admiral-Fish/PokeFinder/commit/048e3d5c23916b2f8f22164a28f4ff471b81ab41)
