### ISSUE TITLE
Issue with pull down menu on Asus laptop. 

### ISSUE THREAD

**Issue by Jiimmb0** [Admiral-Fish/PokeFinder#423]
I ran into an issue on my laptop (Asus 15.6 inch). Whenever l want to select a nature or a hidden power the first two letters are not visible due to the checkboxes from the pull down menu block them out. Added a picture of the instance happening. 

![IMG_0580](https://github.com/user-attachments/assets/bff35bc9-3087-4609-b961-9e5a146b66ac)

**Comment by Real96** [comment]
> I ran into an issue on my laptop (Asus 15.6 inch). Whenever l want to select a nature or a hidden power the first two letters are not visible due to the checkboxes from the pull down menu block them out. Added a picture of the instance happening.
> 
> ![IMG_0580](https://private-user-images.githubusercontent.com/180873663/365461393-bff35bc9-3087-4609-b961-9e5a146b66ac.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5ODY4NjEsIm5iZiI6MTcyNTk4NjU2MSwicGF0aCI6Ii8xODA4NzM2NjMvMzY1NDYxMzkzLWJmZjM1YmM5LTMwODctNDYwOS1iOTYxLTllNWExNDZiNjZhYy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTBUMTY0MjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTU1NzQzZGZjNGQwYjA2ZmExNDM4Y2NhMDY1NzFlOThjNWYyY2MyYTY3NzBiNzk3YjQxZjc4ZWNlMWU2ZjcwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2On4VL5IPIUXdUB2l93vb7HTpeFD-W6lry1lIWMnxhM)

Can you pls try [latest commit](https://nightly.link/Admiral-Fish/PokeFinder/workflows/windows.yaml/master/PokeFinder-windows.zip) and tell us if the problem is also there?

**Comment by Jiimmb0** [comment]
> > I ran into an issue on my laptop (Asus 15.6 inch). Whenever l want to select a nature or a hidden power the first two letters are not visible due to the checkboxes from the pull down menu block them out. Added a picture of the instance happening.
> 
> 
> 
> Can you pls try [latest commit](https://nightly.link/Admiral-Fish/PokeFinder/workflows/windows.yaml/master/PokeFinder-windows.zip) and tell us if the problem is also there? 

Hey! Yes, still the case. See attached picture. ![image](https://github.com/user-attachments/assets/ba505b9a-eabf-4e86-8779-434a96a68dcf)

**Comment by Admiral-Fish** [comment]
It might be better with the latest commit. I reworked how those dropdown works

**Comment by Real96** [comment]
> > > I ran into an issue on my laptop (Asus 15.6 inch). Whenever l want to select a nature or a hidden power the first two letters are not visible due to the checkboxes from the pull down menu block them out. Added a picture of the instance happening.
> > 
> > 
> > Can you pls try [latest commit](https://nightly.link/Admiral-Fish/PokeFinder/workflows/windows.yaml/master/PokeFinder-windows.zip) and tell us if the problem is also there?
> 
> Hey! Yes, still the case. See attached picture. ![image](https://private-user-images.githubusercontent.com/180873663/366148916-ba505b9a-eabf-4e86-8779-434a96a68dcf.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NzIyODIsIm5iZiI6MTczMTc3MTk4MiwicGF0aCI6Ii8xODA4NzM2NjMvMzY2MTQ4OTE2LWJhNTA1YjlhLWVhYmYtNGU4Ni04Nzc5LTQzNGE5NmE2OGRjZi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTZUMTU0NjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRlODE4M2UyMTE4ODUwNGVlOTZiYmVlZTUxMTE4MWFiZDRlYWVkMmViYTdiMDk2MTllZDA3NzhlMzBiODcxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ywZPgAqzUTBTc-_IkdxKfFo7UnAPxKghcY42HY7_2kI)

Can you try downloading again [latest commit](https://nightly.link/Admiral-Fish/PokeFinder/workflows/windows.yaml/master/PokeFinder-windows.zip) and tell us if the problem still happens?

**Comment by Jiimmb0** [comment]
> > > > I ran into an issue on my laptop (Asus 15.6 inch). Whenever l want to select a nature or a hidden power the first two letters are not visible due to the checkboxes from the pull down menu block them out. Added a picture of the instance happening.
> > > 
> > > 
> > > Can you pls try [latest commit](https://nightly.link/Admiral-Fish/PokeFinder/workflows/windows.yaml/master/PokeFinder-windows.zip) and tell us if the problem is also there?
> > 
> > 
> > Hey! Yes, still the case. See attached picture. ![image](https://private-user-images.githubusercontent.com/180873663/366148916-ba505b9a-eabf-4e86-8779-434a96a68dcf.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NzIyODIsIm5iZiI6MTczMTc3MTk4MiwicGF0aCI6Ii8xODA4NzM2NjMvMzY2MTQ4OTE2LWJhNTA1YjlhLWVhYmYtNGU4Ni04Nzc5LTQzNGE5NmE2OGRjZi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTZUMTU0NjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRlODE4M2UyMTE4ODUwNGVlOTZiYmVlZTUxMTE4MWFiZDRlYWVkMmViYTdiMDk2MTllZDA3NzhlMzBiODcxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ywZPgAqzUTBTc-_IkdxKfFo7UnAPxKghcY42HY7_2kI)
> 
> Can you try downloading again [latest commit](https://nightly.link/Admiral-Fish/PokeFinder/workflows/windows.yaml/master/PokeFinder-windows.zip) and tell us if the problem still happens?

Hey! Problem is fixed!
![Uploading thumbnail_image.png…]()
