### ISSUE TITLE
Linux version not working on Linux Mint MATE 22 Wilma, qt issue

### ISSUE THREAD

**Issue by Iguessthiswasinevitable** [Admiral-Fish/PokeFinder#429]
When attempting to run from terminal, I get 

> error while loading shared libraries: libQt6Widgets.so.6: cannot open shared object file: No such file or directory 

It looks like Wilma doesn't come with the qt libraries out of the box? The most recent version of Linux Mint actually has a bunch of missing (deliberately omitted, usually for good reason) libraries, but I can't figure out how to fix this one. This might be a similar issue to closed ticket #78, but qmake --version doesn't detect qt6 at all, instead only checking for qt5, despite my manually installing both. Here's what I got before installing qt5 qmake but after installing 6:

> qmake --version
> qmake: could not exec '/usr/lib/qt5/bin/qmake': No such file or directory

and after installing both

> qmake --version
> QMake version 3.1
> Using Qt version 5.15.13 in /usr/lib/x86_64-linux-gnu

You can see it's only looking in the qt5 folder. It also looks like most of the stuff officially available through Wilma's default repos is 5, not 6.

For what it's worth, Virtualbox, which uses a qt gui, works fine.

**Comment by Admiral-Fish** [comment]
You need at least Qt 6.8 to build. If your linux distro doesn't have it by default you can install via the Qt website
