### ISSUE TITLE
Qt 6.8 Required

### ISSUE THREAD

**Issue by jkarns275** [Admiral-Fish/PokeFinder#431]
Trying to build on MacOS is giving me this issue:
```
[ 96%] Building CXX object Source/CMakeFiles/PokeFinder.dir/main.cpp.o
/Users/josh/Development/PokeFinder/Source/main.cpp:101:16: error: no member named 'setColorScheme' in 'QStyleHints'
  101 |         hints->setColorScheme(Qt::ColorScheme::Dark);
      |         ~~~~~  ^
/Users/josh/Development/PokeFinder/Source/main.cpp:106:16: error: no member named 'setColorScheme' in 'QStyleHints'
  106 |         hints->setColorScheme(Qt::ColorScheme::Light);
```

`setColorScheme` appears to be new as of 6.8. As the version of Qt that brew currently ships is is 6.7, I think it would be worth it to mention in the build instructions that 6.8 is required.

I added a simple feature gate in the main method to get around this for now:
```
#if QT_VERSION > QT_VERSION_CHECK(6, 8, 0)
    a.setStyle("fusion");
#endif
```

This seems to be a new change as of a recent push. I have a PR that addresses this https://github.com/Admiral-Fish/PokeFinder/pull/430

**Comment by Admiral-Fish** [comment]
Your commit won't work as I removed qdarkstylesheet. I have updated the readme to include the required Qt version. Brew will be updated in time
