### ISSUE TITLE
Quality of Life Improvements

### ISSUE THREAD

**Issue by GammaGames** [Admiral-Fish/PokeFinder#53]
These are just a few (hopefully) simple improvements that could be made I thought of while having my friend walk my through using the new Gen 4 tools:

* Show a down pointing arrow (▼) to the right side of select inputs to indicate that it will open a menu
* Increase padding on tab text
![image](https://user-images.githubusercontent.com/7832163/41329475-340e74ec-6e8b-11e8-893b-2e6227e43067.png)
* Increase seed column in Egg Searcher so that they are wide enough for the containing text
![image](https://user-images.githubusercontent.com/7832163/41329692-5f2300ca-6e8c-11e8-94fb-5d7bf0cb4a8a.png)
* Double click cells in a table to copy text
* Alternatively, double clicking a seed could open a new dialog to select a tool for the current gen, for example:
  1. Use Gen 4 Egg tool to search for a seed with Egg IVs
  2. Double click a Seed cell
  3. Pop up to select either Stationary, Wild, Egg, or Seed to Time tools
  4. Use selects Seed to Time
  5. Since the profile already has the game, the Seed to Time window is opened with the seed entered

I ran these ideas past my friend that wants to use the tool and they said that some of these changes might be handy in general use.  
Thank you for the tool! I like how clean it looks and it is overall super simple to use! :)

**Comment by Admiral-Fish** [comment]
Arrow pointing down should just be simple CSS.

Increase padding for text probably CSS or a simple change to the UI file.

Columns are user resizable. UI spacing is a bit tight for some tableviews so maybe I can increase size of all forms across the board.

Double click to copy text should be a fairly simple mouse event. Would probably be easier then right click -> copy seed which is the current setup plus would work for all cells.

Right click context menus coming to gen 4 soon to cover opening Seed to Time and other stuff like that.
