### ISSUE TITLE
[Gen 3 - 5] Hidden Power IV Searcher

### ISSUE THREAD

**Issue by hexandwhy** [Admiral-Fish/PokeFinder#57]
One of the missing functionalities of the current PokeFinder in comparison to the RNG Reporter is the option to search for Hidden Power IVs. Basically, RNG Reporter has an option to look for IVs that give 70 BP Hidden Powers.

HP Even is 4x+2 IV (2, 6, 10, 14, 18, 22, 26, 30) while HP Odd is 4x + 3 (3, 7, 11, 15, 19, 23, 27, 31).

Doesn't apply to gen 6 and above because HP power isn't determined by IV anymore. Might still be useful to have an even or odd detector for getting certain HP types, but idk.

Edit: Also perhaps a toggle for 0 IVs, but that's not as big a problem, I guess. In fact, the best solution might be able to be the capacity to search for IVs that give a certain HP power. (The ability to search from 30-70)

**Comment by Admiral-Fish** [comment]
I intentionally didn't include this since I didn't think people cared about past gens as much anymore. I figured most people just rng then transfer and BP is 60 in 6+. If enough people want it I could add it in.

> Doesn't apply to gen 6 and above because HP power isn't determined by IV anymore. Might still be useful to have an even or odd detector for getting certain HP types, but idk.

There is a filter option to choose what hidden power type you want.

**Comment by hexandwhy** [comment]
Technically, filtering in HP types and checking for odds and even is slightly different, but I couldn't think of a reason to have that mechanic after a few hours of thought.

Looking for HP Fighting on the calculator can give you:

O/O/E/E/E/E
O/E/E/E/E/E
E/O/E/E/E/E
E/E/O/E/E/E
E/E/E/E/E/E

And maybe narrowing into a certain one could have made the "Searcher" give results slightly faster, but I guess there's no other benefit.

I still would like to advocate for 0 IV toggle (not as vital as you can always set it yourself), but I guess the rest is dependent on the demand of other people. (I assume nobody would care that much)
