### ISSUE TITLE
[FRLG Egg] Frames are impossible to hit.

### ISSUE THREAD

**Issue by RichardPaulAstley** [Admiral-Fish/PokeFinder#58]
Little simple bug but with PokeFinder, when you target an egg's frame, both step generation frame + retrive frame are wrong of a few frames. Could be linked to some calibration not present in PokeFinder.

No issue with RNG Reporter about that.

**Comment by Admiral-Fish** [comment]
Can't replicate. Seems completely fine to me. Would need an example.

**Comment by Admiral-Fish** [comment]
This is due to an offset that I added into reporter.

Somewhat related to this ffb0c87 fixed an inheritance issue.
