### ISSUE TITLE
All Gens : TID / SID management 

### ISSUE THREAD

**Issue by RichardPaulAstley** [Admiral-Fish/PokeFinder#6]
Repost from RNGReporter since you approved it :

A way to have a little menu for putting all TID / SID along with the correct game. This way when loading the right generation RNG, a list with TID / SID available could be present in the tool (like profiles with Gen 5 in RNG Reporter) and people would just have choose their games. 

And on the main windows (if similar to RNG Reporter), a list with ALL games, no generation specific.

Thanks o/

**Comment by Admiral-Fish** [comment]
Probably have a separate manager for each gen. I plan on having the GUI separate for each gen for easier code management (and so it's more user friendly?).

**Comment by RichardPaulAstley** [comment]
Well, thanks for the answer and to add this to the project really.

After the idea of separate GUI for each gens resolve the problems, and if you want my opinon it's really more user friendly yes. Really a good idea rather than the main windows and the time finder lost somewhere o/

Thanks again !

**Comment by Admiral-Fish** [comment]
Profiles implemented for gens 3-5. Will be added once gen6/7 is reached. Gonna close this
