### ISSUE TITLE
[Gen 4] Guess what ? Fishing is broken. 

### ISSUE THREAD

**Issue by RichardPaulAstley** [Admiral-Fish/PokeFinder#60]
So after one hour of brain melting. Here's some stuff i've found and that need to be fixed.

On this test i'm targeting a Shiny Lumineon (Encounter Slot 1) on Frame 9. WITH Suction Cups. 

I've used RNG Reporter for that. after failing hard with PokeFinder. I searched a Non lead spread, and got my Shiny on Frame 9 WITH Suction Cups. But we know that's also broken. 

![image](https://user-images.githubusercontent.com/25870563/46702875-24ea6f00-cc25-11e8-9d96-936642382e06.png)
^The proof of the struggle.

SO. I compared with PokeFinder results. Since you fixed Lead, i did the research with the GOOD lead. And here's the result : 

![image](https://user-images.githubusercontent.com/25870563/46702970-7f83cb00-cc25-11e8-8f48-fea4898296d2.png)

As you can see the PID is set to the frame AFTER aand you can see a difference on every frame.

So. I got it to work on RNG Reporter with ignoring the lead fact ALMOST matching PokeFinder's result even if there's one frame difference.

An offset or idk, but i just want to rest now.

**Comment by Admiral-Fish** [comment]
Is this issue for HGSS, DPPt, or both?

**Comment by Admiral-Fish** [comment]
After some testing it appears that suction cups does not work in Sinnoh. Still need to test more for HGSS. Working on frame offsets.

**Comment by Admiral-Fish** [comment]
3d14541 should have fixed DPPt.

Still need to look at HGSS.

**Comment by Admiral-Fish** [comment]
4a73fe2 and 3d14541 should fix this. Gonna close for now unless someone finds other issues.
