### ISSUE TITLE
[Gen 3] Eggs - Ruby/Sapphire PID/IV

### ISSUE THREAD

**Issue by CyZnRg** [Admiral-Fish/PokeFinder#62]
RNGing a matching PID results in seemingly random IVs inconsistent with the results of PokéFinder.

![example](https://user-images.githubusercontent.com/37464785/50004871-7a6d3000-ff76-11e8-9be0-e42705495792.png)

**Comment by Admiral-Fish** [comment]
What version or commit of pokefinder are you using?

**Comment by CyZnRg** [comment]
The latest release 2.2.0 (Properties > Details says 2.1.0); just re-downloaded to confirm.

**Comment by Admiral-Fish** [comment]
Could you try hitting that frame again but with different parent IVs? Like have parent1 be 0.1.2.3.4.5 and parent2 be 6.7.8.9.10.11?

Hard for me to map things out when parents are both 31s.

**Comment by CyZnRg** [comment]
![example_2](https://user-images.githubusercontent.com/37464785/50038660-e5f3e380-fff0-11e8-9801-087a320601d8.png)

**Comment by Admiral-Fish** [comment]
Appears to be some weird vblank calls maybe?

I have it as 
seed -> pid -> blank -> iv -> iv -> blank -> inh1 -> inh2 -> inh3 -> par1 -> par2 -> par3

Looks like you are getting
seed -> pid -> blank -> iv -> iv -> blank -> blank -> inh1 -> inh2 -> inh3 -> par1 -> par2 -> par3

Blank is either unused or vblank. Most likely vblank looking at the game assembly https://github.com/pret/pokeruby/blob/master/src/daycare.c#L666

I tried an egg or two but didn't get the calls lining up the way you did. Have you modified your game rom in anyway?

**Comment by Admiral-Fish** [comment]
https://www.smogon.com/forums/threads/past-gen-rng-research.61090/page-30#post-3642140
https://www.smogon.com/forums/threads/past-gen-rng-research.61090/page-34#post-4013655

Dumping these for later reference

**Comment by Admiral-Fish** [comment]
Using data from a retail Ruby I have found two patterns.

The majority use
Start -> pid -> blank -> iv -> iv -> blank -> inh1 -> inh2 -> inh3 -> par1 -> par2 -> par3

While a smaller amount use
Start -> pid -> iv -> blank -> iv -> blank -> inh1 -> inh2 -> inh3 -> par1 -> par2 -> par3

**Comment by Admiral-Fish** [comment]
6f7370d starts to address this
