### ISSUE TITLE
Headbutt HGSS RNG

### ISSUE THREAD

**Issue by Orionsilver** [Admiral-Fish/PokeFinder#71]
Add Headbutt Pokémon for Pokemon HGSS on Pokefinder

**Comment by RichardPaulAstley** [comment]
No need too. Capture supports it well. If you need to learn how to do it :

https://github.com/zaksabeast/PokemonRNGGuides/blob/add/hgss/en/specialwild/guides/hgss/en/HGSS%20Special%20Wild%20Case%20(emu).md

^There are notes atm i did from all the RNG i've tried / done.
100% working with these.

**Comment by Real96** [comment]
Added in a31213f
