### ISSUE TITLE
XD/Colo Searcher

### ISSUE THREAD

**Issue by kamronbatman** [Admiral-Fish/PokeFinder#75]
Looks like XD/Colo Searcher is not giving the right PID for the seed.
<img width="1176" alt="Screen Shot 2019-06-02 at 8 06 39 PM" src="https://user-images.githubusercontent.com/3953314/58773489-1238f780-8572-11e9-864c-dff7a1ab0c22.png">
<img width="1183" alt="Screen Shot 2019-06-02 at 8 06 31 PM" src="https://user-images.githubusercontent.com/3953314/58773491-136a2480-8572-11e9-8c2e-26cc426baea2.png">

And to be clear, the generator does give the right result.

**Comment by Admiral-Fish** [comment]
Should be fixed by d5309f1

**Comment by kamronbatman** [comment]
I'll test when I get a chance

**Comment by Admiral-Fish** [comment]
Gonna close. Let me know if I need to reopen if it isn't fixed.
