### ISSUE TITLE
Implement Show IVs as Stats

### ISSUE THREAD

**Issue by jjaldridge2009** [Admiral-Fish/PokeFinder#76]
Adding an option to check a box and specify a Target Pokemon & Level and convert IV spreads to In-Game stat values would be very useful in Gen 3 \ XDColo on retail. 

We do a lot of checking Pokemon across attempts to hit seeds, and having to calculate IVs to stats every time adds a lot of time to each run trying to hit a seed.

Obviously an enhancement and "nice to have" but I thought I'd add it here since I think Fish has mentioned it before.

**Comment by Admiral-Fish** [comment]
How exactly would you suggest it operate? I looked at 3dsrngtool as an example (https://gyazo.com/70ec5e1724bc28137f30f4d9057c8f91).

Do you have another idea in mind or something like how wwwwwwzx did it?

**Comment by jjaldridge2009** [comment]
Yeah that's actually exactly what I was thinking of when I made the suggestion. I don't know why I didn't just reference that directly. 

Manually setting the base stats would obviously be workable, or selecting the Pokemon from a drop down would be amazing.

**Comment by Admiral-Fish** [comment]
Completed in 149f2cf. As the redesign branch continues everything will have an option to show stats
