### ISSUE TITLE
Linux version not working

### ISSUE THREAD

**Issue by remokon** [Admiral-Fish/PokeFinder#78]
Hey admiral, I've been trying to make the linux version on Ubuntu 18.04 with no success. Made sure to enable the "running as executable" property, but nothing changed. 
How is it supposed to be run? I've checked the repo but I couldn't find any readme or helper that mentioned the Linux version.

Thanks.

**Comment by brainard52** [comment]
When you're running it, how are you doing so?

If you run it from terminal, what messages are printed?

**Comment by remokon** [comment]
By running I mean both on double click on the extracted file to be found in the Pokefinder-linux.zip archive, and by using xdg-open from terminal. These where my wild guesses on how to make it work. 
Here, `xdg-open` complains about not having a proper program to run it with:
```
gio: file:///home/<USER>/Downloads/pokefinder-linux/PokeFinder: No application is registered as handling this file
```
Thanks for your help.

**Comment by brainard52** [comment]
if the executable bit is set, you can do /home/<USER>/Downloads/pokefinder-linux/PokeFinder in terminal and it will launch it. xdg-open just sends a URL intent, and if nothing knows how to handle an executeable file it will result in that error.

**Comment by remokon** [comment]
Oh ok thanks! Now apparently I'm only missing some libraries:

```
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found
```

for which after a research I ended up trying to attach `/usr/lib/x86_64-linux-gnu/` to the env var `LD_LIBRARY_PATH`. Nothing changed though. So I checked the actual version of it and I actually got this:

```
╰─$ qmake --version                  
QMake version 3.1
Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu

```
And when I try to reinstall it I actually see that the latest version for ubuntu 18.04 is indeed 5.9.5

```qt5-default is already the newest version (5.9.5+dfsg-0ubuntu2.1).```

So I went over their website and downloaded the .run file to perform the installation, choose 5.12.4 as the preferred version and I was very surprised to see it's almost 8gb. Do I really need this much just for PokeFinder? :sweat_smile:

**Comment by brainard52** [comment]
It looks like 18.04 has out of date libs. Is there any reason you haven't dist-upgraded to 19.04?

**Comment by Admiral-Fish** [comment]
Pretty sure 19.04 has Qt 5.12. I just use a ppa to install Qt 5.12 on early ubuntu versions https://github.com/Admiral-Fish/PokeFinder/blob/develop/appveyor.yml#L24-L27.

Although if you build the latest commit from source it only requires Qt 5.9 https://github.com/Admiral-Fish/PokeFinder/blob/develop/PokeFinder.pro#L1-L2. I just build against 5.12

**Comment by brainard52** [comment]
I can confirm that 19.04 distributes Qt 5.12. That's why I mentioned it. How challenging would it be to build one release each for the two most recent short-term release and long-term release versions of Ubuntu?

**Comment by Admiral-Fish** [comment]
Well the issue is that the current release relies on specific Qt 5.12 additions. I changed that in recent commits to rely on Qt 5.9. Qt is binary compatible within the minor version changes https://wiki.qt.io/Qt-Version-Compatibility. So even though I build againist 5.12 it will run against 5.9 and earlier as long as I am not using any features that were added in a specific update.

**Comment by remokon** [comment]
> Is there any reason you haven't dist-upgraded to 19.04?
I've always used the latest LTS for Ubuntu, and most of the people I know that use Ubuntu — even all of CS colleagues, while I'm not :smile: — do the same. So until 20.04, I won't upgrade.

@Admiral-Fish I'm not that big of an expert as far as building stuff from source is concerned, would you mind adding a couple of lines in the README or write here how to do that for the latest release? :pray:

**Comment by brainard52** [comment]
> I've always used the latest LTS for Ubuntu, and most of the people I know that use Ubuntu — even all of CS colleagues, while I'm not 😄 — do the same. So until 20.04, I won't upgrade.

I didn't realize LTS was every other .04 release.

**Comment by Admiral-Fish** [comment]
Alright I changed the build script for linux to use Qt 5.9 #80. Can download a build from appveyor(https://ci.appveyor.com/project/Admiral-Fish/pokefinder) or wait for the next release.

If you want to build from source you would clone the repo and the submodule. These are the required packages to build(build-essential qtbase5-dev qt5-qmake qt5-default). Then you cd into the cloned folder and run qmake PokeFinder.pro then make.

**Comment by remokon** [comment]
Built it from source, worked perfectly. 
Thanks a lot and keep up the great work for the upcoming Gens.
