### ISSUE TITLE
[Gen 4] Crashes on Windows when searching for wild pkmn results

### ISSUE THREAD

**Issue by remokon** [Admiral-Fish/PokeFinder#79]
How to reproduce:

In the Gen 4 wild encounter tab for DPPt I tried to run the search with these inputs:
- Method J
- Wayward Cave (Secret)
- Morning
- Gible
- Grass
- Cute Charm
- 00200
- 00197

IVs: all 31

Gender: F
Hasty
5,8,10
/
Gender Ratio: 50/50
Delay: 400 - 6000
Frame: 1 - 400

Then after hitting the search button 6 results pop up, but also the system message "PokeFinder has stopped working". 

If I limit the search to a more restrictive max delay such as 3000, everything works fine.

**Comment by Admiral-Fish** [comment]
Can't replicate.

Are you using the latest release or the latest commit?

**Comment by NeccoWafer** [comment]
I can confirm this happens on both latest commit and release for me as well.

**Comment by Admiral-Fish** [comment]
@NeccoWafer Can you give search settings and when more specifically it crashes?

**Comment by NeccoWafer** [comment]
Odd so I used the same parameters @remokon. Just deleted PokeFinder and re downloaded it, and it doesn’t crash anymore.

**Comment by Admiral-Fish** [comment]
@remokon Try again with 2.4.1

**Comment by remokon** [comment]
@Admiral-Fish tried w/ 2.4.1 and it's doing just fine.

Incidentally, just saw you fixed the Chatot pitches bug, I remember having issues with it even when hitting the correct delay, I'm eager to re-test it soon!

Closing.
