### ISSUE TITLE
Multi Language Support

### ISSUE THREAD

**Issue by Admiral-Fish** [Admiral-Fish/PokeFinder#8]
- [x] English

- [ ] Spanish

- [x] Italian

- [x] French

- [ ] Japanese

- [ ] Korean

- [ ] German

- [ ] Chinese

Make sure translation changes are applied to the develop branch as it has the most up to date code.

**Comment by Admiral-Fish** [comment]
@pkmnbumba What are your thoughts on this?

**Comment by pkmnbumba** [comment]
Yeah this could be a good idea. Would be hard for some of these haha

**Comment by RichardPaulAstley** [comment]
I can help for French if needed ?

**Comment by Sasasu** [comment]
I will add chinese translate.

**Comment by Admiral-Fish** [comment]
@Sasasu Awesome. Do you know how to change the translation files or do you need some instructions?

**Comment by Sasasu** [comment]
@Admiral-Fish 
Nope, The English version is very clear and easy to translate.
master branch is little confused, but the develop branch is very clear.

**Comment by Admiral-Fish** [comment]
@Sasasu Yeah sorry about that. Probably should have clarified in original comment that changes should be worked on the develop branch. Master is more like the official release branch while develop is where all the changes happen.

**Comment by hndr91** [comment]
Can I work for Indonesian ?

**Comment by Admiral-Fish** [comment]
@hndr91 Sure. Do you know how to add the language files or should I?

**Comment by hndr91** [comment]
Still didn't get it, what .qm files do @Admiral-Fish

**Comment by Admiral-Fish** [comment]
@hndr91 Unless I'm missing something I don't see it listed here http://doc.qt.io/qt-5/internationalization.html

**Comment by hndr91** [comment]
I should use QtLinguist right ? @Admiral-Fish

**Comment by hndr91** [comment]
Ohh, ok I see, id isn't listed

**Comment by Admiral-Fish** [comment]
Translations will be up to the users to do whenever they feel like updating them. Gonna go ahead and close this unless someone really wants me to keep it open.
