### ISSUE TITLE
crashes when looking for too many results

### ISSUE THREAD

**Issue by Araraura** [Admiral-Fish/PokeFinder#82]
the program crashes if I'm trying to look for more than 1 billion results. I noticed this doesn't happen with RNGReporter, but in pokefinder, it just closes when I look for somewhere more than 1 billion.

**Comment by Admiral-Fish** [comment]
That is your computer running out of memory. I precalculate all the random numbers that are needed and then just grab them as I go.

I can look into seeing if caching less and having to generate more of the numbers while the search runs is a viable option in terms of speed (aka a speed vs storage tradeoff).

For right now just search through a smaller amount.

**Comment by Admiral-Fish** [comment]
Fixed by #84
