### ISSUE TITLE
Chain shiny HGSS

### ISSUE THREAD

**Issue by notblisy** [Admiral-Fish/PokeFinder#83]
Chain shiny search method does not appear for HGSS, while the PokeRadar does not exist in these games, Red Gyarados actually uses this method for generation. I think allowing it to be selected in HGSS should be enabled, or even just name the category "red gyarados" since it's the only Pokemon in HGSS to use this generation method, as right now we'd have to make a fake DPP profile to search for a spread

**Comment by Admiral-Fish** [comment]
Fixed by #84
