### ISSUE TITLE
Spinda Painter constructs PID in wrong order

### ISSUE THREAD

**Issue by phijor** [Admiral-Fish/PokeFinder#88]
I'm trying to use the Spinda Painter to help me with Emerald Egg RNG.
Apparently, when decoding the PID from position of its spots, the 8 nibbles that make up the full PID are ordered exactly the wrong way around.

Steps to reproduce:

* enter Emerald egg RNG tool
* select method _PID_
* set calibration to 19
* set redraws to min 0/max 0
* generate frame 4691
* note down **PID of `44cf67e8`**

and now, try to match a Spinda generated on this frame:

* open Spinda painter
* enter spots like this:
![2020-03-18_175245](https://user-images.githubusercontent.com/10487782/76986214-a3caf780-6941-11ea-939a-b65fbe7a1a8a.png)
* compare to spots generated on cartridge (language is german): 
![image](https://user-images.githubusercontent.com/10487782/76986498-045a3480-6942-11ea-9030-bd9c6a1f5d6d.png)
* note that now the **PID is `8e76fc44`**

I think these two lines are wrong:

https://github.com/Admiral-Fish/PokeFinder/blob/2f008a6e0cc9ad58f086c85bf582dc8a59c3b25a/Forms/Gen3/Tools/SpindaPainter.cpp#L128-L129

they should be something like
```cpp
 pid |= (left << (i * 8 + 0)); 
 pid |= (right << (i * 8 + 4)); 
```

**Comment by Admiral-Fish** [comment]
Thanks for pointing out the fix
