### ISSUE TITLE
Arch Linux user repository (AUR) packages

### ISSUE THREAD

**Issue by phijor** [Admiral-Fish/PokeFinder#90]
I set up packages to install PokeFinder from the AUR. There are two packages:

* [`pokefinder`](https://aur.archlinux.org/packages/pokefinder/): installs the binary files provided in the Github release section
* [`pokefinder-git`](https://aur.archlinux.org/packages/pokefinder-git/): builds the most recent git commit and installs the resulting binary

Feel free to add links to packages to the README, or ask me to draft a PR to include some information how to install them on Arch Linux.

Thank you for your work, it's nice having a cross-platform RNG framework that does it's job well :)

**Comment by Admiral-Fish** [comment]
I'm not familiar with AUR. Would you care to elaborate?
