### ISSUE TITLE
Wild searcher for Gen 4 IV values are off by one column  to the left

### ISSUE THREAD

**Issue by HardRockDota** [Admiral-Fish/PokeFinder#93]
Using the version 2.5.1 on Windows. For example, if you imput 20-25 IVs on Speed, it will register it on SpD and so on. So every pokemon searched has either 0 or 1 Speed IVs :(
![image](https://user-images.githubusercontent.com/63575447/79094688-f075d880-7d1d-11ea-8695-b2026230d37b.png)

**Comment by Admiral-Fish** [comment]
Actually was an array out of bounds read. Interesting how it always resulted in 0 or 1. Looks like it might have been reading from the ability field.
