### ISSUE TITLE
Problems Building Pokefinder and EonTimer on Debian Linux (Chromebook)

### ISSUE THREAD

**Issue by tha-chunginator** [Admiral-Fish/PokeFinder#94]
I have almost no coding experience and have had multiple problems in building these RNG programs. 
I followed the directions on how to build them, but my Linux system encountered multiple problems while downloading dependencies:
gpg: keybox '/tmp/tmpa0byif8g/pubring.gpg' created
gpg: /tmp/tmpa0byif8g/trustdb.gpg: trustdb created
gpg: key 10C56D0DE9977759: public key "Launchpad PPA for Stephan Binner" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
I don't know what this means, and I am not very clear on how to build these softwares overall. I am not sure if I have the wrong system, or the source of the problem is entirely different. Help would be greatly appreciated.

**Comment by tha-chunginator** [comment]
I found out that the dependencies aren't compatible with Debian, and were made for Ubuntu. Can I still build PokeFinder from source?

**Comment by Admiral-Fish** [comment]
PokeFinder currently requires at least Qt 5.10. If you can get Qt 5.10 on Debian you should be able to build PokeFinder.

**Comment by tha-chunginator** [comment]
So then I need to install Qt 5.10 on my debian system before following the instructions on the READ.me. Got it. Is that why linux couldn't find the dependencies? I hadn't downloaded anything previously.

**Comment by tha-chunginator** [comment]
Apparently I already had the latest version. this is what it said when I typed in sudo apt-get install build-essential libgl1-mesa-dev:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.6).
libgl1-mesa-dev is already the newest version (19.2.8~cros1).
libgl1-mesa-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by tha-chunginator** [comment]
Downloading dependencies failed again, results in 
gpg: keybox '/tmp/tmpa0byif8g/pubring.gpg' created
gpg: /tmp/tmpa0byif8g/trustdb.gpg: trustdb created
gpg: key 10C56D0DE9977759: public key "Launchpad PPA for Stephan Binner" imported
gpg: Total number processed: 1
gpg: imported: 1
gpg: no valid OpenPGP data found.
Am I doing something wrong? Thanks for the help.

**Comment by tha-chunginator** [comment]
It appears that there isn't anything in the folder QdarkStyleSheet, and the system is having problems building PokeFinder.pro. It loops over and over again about QdarkStyleSheet not existing.

**Comment by Admiral-Fish** [comment]
Well I have only ever built PokeFinder on Ubuntu so I'm not super familiar with Debian. After some quick research it looks like Debian version "buster" (the latest stable release) has Qt 5.11 as the version of Qt https://packages.debian.org/buster/qt5-default. So if you install that it should be good and you won't have to worry about the ppa (especially since I'm pretty sure that only works on Ubuntu).

For QDarkStyleSheet, it is a submodule so you will have to initialize it properly. You can find git commands on how to do that online fairly easily.

**Comment by tha-chunginator** [comment]
When I tried to install those it told me that I already had the latest version and it didn't install anything. I must already have previously installed it when I was messing around with it earlier.

**Comment by tha-chunginator** [comment]
When I ran git submodule init, after opening the QDarkStyleSheet directory, it said:
fatal: not a git repository (or any of the parent directories): .git
Am I initializing the wrong folder?

**Comment by tha-chunginator** [comment]
I apologize for my ignorance... :-/

**Comment by tha-chunginator** [comment]
Ok so I figured out that 'submodule' was messing with it so I just ran git init and got:
Initialized empty Git repository in /home/kingofkrisskrossover/PokeFinder-master/QDarkStyleSheet/.git/
then I went back to the PokeFinder-master directory and tried to qmake Pokefinder.pro again. this resulted in 
WARNING: Failure to find: QDarkStyleSheet/qdarkstyle/style.qrc
/usr/lib/qt5/bin/rcc: File does not exist 'QDarkStyleSheet/qdarkstyle/style.qrc'
I thought that I just initialized it. Whats the issue?

**Comment by Admiral-Fish** [comment]
I usually just type `git submodule update --init --recursive`

**Comment by tha-chunginator** [comment]
I typed git submodule update --init --recursive while in the folder and it did nothing. Afterwords, I tried qmake PokeFinder again in the directory for PokeFinder master, and it still can't find QDarkStyleSheet/qdarkstyle/style.qrc to qmake Pokefinder because it doesn't exist. I don't think I ended up initializing anything.

**Comment by tha-chunginator** [comment]
after typing git submodule update --init --recursive after making sure I was in the QDarkStyleSheet directory, The system said that it was not a git repository (or any of the parent directories). what should I do?

**Comment by tha-chunginator** [comment]
Should I download the same file from another scource?

**Comment by tha-chunginator** [comment]
Ok I got much farther, but now, in the middle of synthesizing the app, linux says:
Core/Util/Translator.cpp: In function ‘QStringList Translator::getSpecies(const QVector<short unsigned int>&)’:
Core/Util/Translator.cpp:98:24: error: range-based ‘for’ expression of type ‘const QVector<short unsigned int>’ has incomplete type
         for (u16 num : nums)
                        ^~~~
Core/Util/Translator.cpp: In function ‘QStringList Translator::getLocations(const QVector<unsigned char>&, Game)’:
Core/Util/Translator.cpp:139:30: error: range-based ‘for’ expression of type ‘const QVector<unsigned char>’ has incomplete type
         for (const u8 &num : nums)
                              ^~~~
make: *** [Makefile:2521: Translator.o] Error 1
make: *** Waiting for unfinished jobs....
I don't if I can decipher this. Any ideas?

**Comment by Admiral-Fish** [comment]
I haven't seen an error like that before. I have two thoughts. Can start by trying adding `#include <QVector>` at the top of Translator.hpp. Otherwise I would verify you are using a compiler with c++17 support.

**Comment by tha-chunginator** [comment]
Okay that got past that error. Now what is the last step?

**Comment by Admiral-Fish** [comment]
Well assuming the build finished successfully, you should have a binary file called PokeFinder. Just run that, `./PokeFinder` should work

**Comment by tha-chunginator** [comment]
Sweet! Thanks So much for all your help! I learned a lot during this process, keep up the great work!
