### ISSUE TITLE
PID and TID Filters for Ruby/Sapphire TID/SID RNG are slightly off

### ISSUE THREAD

**Issue by Sephirona** [Admiral-Fish/PokeFinder#97]
Hi there! It's a small issue but I thought you might want to know that when both boxes for PID and TID are checked in Pokefinder Gen III RS, the TID/SID spreads generated are only for the TID search and not for the PID search, so the TID/SID combos that show up cannot be shiny despite the PID box also being checked. This isn't a big deal if people take the time to double check the TID/SID combo they are trying for by plugging it into the main windows to make sure it results in a shiny spread, but I noticed this filter works properly in your fork of RNGReporter so that's why I thought perhaps the filters for Pokefinder aren't working as you intended.

**Comment by Admiral-Fish** [comment]
Could you give an example?

**Comment by Sephirona** [comment]
Sorry, I would have attached an example earlier but I had done the RNG a while back and didn't save any screenshots at the time. Here's two pictures to show what I mean:

In the first one, I put in the PID with a dead battery with the TID box unchecked and the TIDs were generated fine, but when I checked PID and TID at the same time, rather than show me if there are possible shiny TID/SID combos with my intended TID for that PID, it just generates me a list of all the TID combos. As you can see, that first TID/SID combo does not make the PID shiny:

![pokefinderrstid](https://user-images.githubusercontent.com/62824439/81627045-45634800-93cb-11ea-9ecb-31b8decf6351.png)

The same two boxes checked on RNGReporter do not do this:

![rstid](https://user-images.githubusercontent.com/62824439/81627163-92471e80-93cb-11ea-8a05-2355e201f5c7.png)

Anyway it's just a small issue, not a big deal, I just figured it might cause people to accidentally RNG for that TID thinking that it would also make that PID shiny if they don't double check beforehand to make sure~

**Comment by Admiral-Fish** [comment]
It was using the XD PID field, which can be used as a workaround for now
