### ISSUE TITLE
Method J&K Stationary off by 1

### ISSUE THREAD

**Issue by greenDarkness** [Admiral-Fish/PokeFinder#98]
Stationary mode for method J & K in the gen 4 section is off by 1, and therefore the generator and searcher do not match. I'm pretty sure this is caused by the first frame not being displayed, and instead frame 2 is displayed as frame 1 for the generator.
This only applies for cute charm in this way.

However, synchronize is wrong as well, but in a different way. Searcher says target frame is 4, however if you do 3 advancements, you will get frame 3 not frame 4. Alternately 4 advancements will give you frame 4, and not frame 5 as it should.

**Comment by Admiral-Fish** [comment]
Does d822c42 fix this?

**Comment by greenDarkness** [comment]
So I tested for method K, and my calls and Chatot pitches lined up as they should, and my encounter matched my target frame. So K is fixed. 
I'll check Method 1 HGSS, J, and Method 1 Pt in a sec.
