### ISSUE TITLE
Searcher is Broken for Gen 4

### ISSUE THREAD

**Issue by greenDarkness** [Admiral-Fish/PokeFinder#99]
Searcher on build `9bcca091b455af7464bd8354ce0c46035609097f` of Pokefinder yields false positive searches.
Example:
User searches for a Modest 31/31/31/31/31/31 Ditto on route 34.
Pokefinder says that on seed 52140289 frames 90 and 91 are perfect ditto.
However, if you check the generator for the results:
```
90	P	Low (10)	7	10	F9426F72	No	Modest	0	31	31	31	31	31	31	Dark	70	-
91	E	Mid-Low (23)	9	10	9180BFE4	No	Brave	0	25	4	24	3	3	5	Ice	60	-
```
Ditto is encounter slots 9,11. 
I think the generator is grabbing encounter slots 1 frame below the target search.

**Comment by greenDarkness** [comment]
`c80795bd2719e8afad892495ebfcc493212a834f` does not completely fix this issue.
Given the above search criteria, this is one of the results:
```
Seed	Frame	Lead	Slot	Level	PID	Shiny	Nature	Ability	HP	Atk	Def	SpA	SpD	Spe	Hidden	Power	Gender
52140289	91	Synchronize	9	10	F9426F72	No	Modest	0	31	31	31	31	31	31	Dark	70	-
```
If you generate frames using seed `52140289`, and check frames 90-91 you get this:
```
Frame	Call	Chatot	Slot	Level	PID	Shiny	Nature	Ability	HP	Atk	Def	SpA	SpD	Spe	Hidden	Power	Gender
90	P	Low (10)	7	10	F9426F72	No	Modest	0	31	31	31	31	31	31	Dark	70	-
91	E	Mid-Low (23)	9	10	9180BFE4	No	Brave	0	25	4	24	3	3	5	Ice	60	-
```

**Comment by Admiral-Fish** [comment]
There seems to be an underlying issue with how the backend searcher works. I don't have the patient for this right now so I'll look more into it later.
